// The coach's notes on the opening moves, written to the user: White in the Italian, Black in the Caro-Kann.
import type { OpeningId } from '../content/types';

export interface Family {
  /** Stable id; also the id of the plan's note, so the store counts when the user met the family. */
  id: string;
  name: string;
  /** Moves from the initial position to the family's first position; extra lines are other move orders. */
  lines: string[];
  /** Shown where the family starts; null for the opening's trunk, which has no single plan. */
  plan: string | null;
  /** Why each move is played, keyed by the moves after the family's first line. */
  notes: Record<string, string>;
}

const IT = 'e4 e5 Nf3 Nc6 Bc4';
const CK = 'e4 c6';
const CK_MAIN = `${CK} d4 d5 Nc3 dxe4 Nxe4`;
const CK_ADVANCE = `${CK} d4 d5 e5`;

/** 1.e4 starts both openings, so its note suits either side. */
const KINGS_PAWN: Family = {
  id: 'kings-pawn',
  name: "King's Pawn Opening",
  lines: [''],
  plan: null,
  notes: { e4: '1.e4 takes the centre and opens lines for the queen and the light-squared bishop.' },
};

const ITALIAN: Family[] = [
  {
    id: 'italian',
    name: 'Italian Game',
    lines: [''],
    plan: null,
    notes: {
      'e4 e5': "1...e5 claims an equal share of the centre and frees Black's queen and dark-squared bishop.",
      'e4 e5 Nf3': '2.Nf3 develops with a threat: the knight attacks the pawn on e5.',
      'e4 e5 Nf3 Nc6': '2...Nc6 defends e5 with a developing move and keeps an eye on d4.',
      [IT]: "3.Bc4 aims the bishop at f7, the weakest square in Black's camp: only the king defends it.",
      [`${IT} f6`]: "3...f6 holds e5 but takes the knight's best square and weakens Black's king. Open lines with d4.",
    },
  },
  {
    id: 'giuoco-piano',
    name: 'Giuoco Piano',
    lines: [`${IT} Bc5`],
    plan: "3...Bc5 points Black's bishop at f2, as yours points at f7. Build the centre with c3 and d4, or play slowly with d3.",
    notes: {},
  },
  {
    id: 'giuoco-piano-c3',
    name: 'Giuoco Piano: 4.c3',
    lines: [`${IT} Bc5 c3`],
    plan: '4.c3 prepares d4, which hits the bishop and takes the centre. If Black takes on d4, recapture with the c-pawn.',
    notes: {
      Nf6: '4...Nf6 attacks e4. With your pawn on c3, the knight can no longer defend it from there, so act with d4 or d3.',
      'Nf6 d4': '5.d4 hits the bishop and e5 together. Black usually takes, and you recapture toward the centre.',
      'Nf6 d4 exd4': '5...exd4 releases the tension. 6.cxd4 builds your centre, but Black gets a check on b4.',
      'Nf6 d4 exd4 cxd4': '6.cxd4 gives you pawns on e4 and d4. Black must hit them now, or e5 and d5 will kick both knights.',
      'Nf6 d4 exd4 cxd4 Bb4+': '6...Bb4+ gains time with a check. 7.Bd2 is the safe block; 7.Nc3 offers the e4 pawn.',
      'Nf6 d4 exd4 cxd4 Bb4+ Bd2': '7.Bd2 blocks and offers to trade bishops. After ...Bxd2+ Nbxd2 your knight guards e4.',
      'Nf6 d4 exd4 cxd4 Bb4+ Bd2 Bxd2+': '7...Bxd2+ trades. Take back with the b1 knight so it covers e4; Black hits back with ...d5.',
      'Nf6 d4 exd4 cxd4 Bb4+ Bd2 Nxe4': '7...Nxe4 grabs a pawn, but 8.Bxb4 Nxb4 9.Bxf7+ Kxf7 10.Qb3+ wins the knight on b4 back.',
      'Nf6 d4 exd4 cxd4 Bb4+ Nc3': '7.Nc3 develops and offers e4. After 7...Nxe4 8.O-O you get open lines and a lead in development.',
      'Nf6 d4 exd4 cxd4 Bb4+ Nc3 Nxe4': '7...Nxe4 takes and piles up on your pinned c3 knight. 8.O-O breaks the pin.',
      'Nf6 d4 exd4 e5': '6.e5 kicks the knight at once. Black hits back with 6...d5, attacking your bishop.',
      'Nf6 d3': '5.d3 keeps e4 solid and plays slowly: castle, Re1 and Nbd2, then d4 later. This is the Giuoco Pianissimo.',
      'Nf6 d3 d6': '5...d6 supports e5 and frees the c8 bishop. Castle, then Re1, Nbd2 and h3 before d4.',
      'Nf6 d3 O-O': "5...O-O tucks Black's king away. Castle too; both sides manoeuvre before d4 or ...d5.",
      'Nf6 d3 a6': '5...a6 gives the bishop a retreat on a7, safe from your d4 and b4.',
      'Nf6 d3 h6': '5...h6 stops Ng5 and Bg5. Castle and play Re1; Nbd2-f1-g3 is a typical regrouping.',
      'Nf6 d3 d5': '5...d5 strikes in the centre. After 6.exd5 Nxd5 the knight is active, but e5 can become a target.',
      Qe7: '4...Qe7 adds a defender to e5, so Black can meet d4 with ...Bb6 and keep a pawn in the centre.',
      'Qe7 d4': '5.d4 claims the centre. Black holds e5 with 5...Bb6; castle and keep up the pressure.',
      h6: '4...h6 stops Ng5 and Bg5 but spends a move. Use it: 5.d4 hits the bishop and e5.',
      'h6 d4': '5.d4 hits the bishop and e5. After 5...exd4 6.cxd4 you have two pawns side by side in the centre.',
      'h6 d4 exd4': '5...exd4 opens the centre. Retake with 6.cxd4: the bishop must check on b4 or drop back.',
      'h6 d4 exd4 cxd4': '6.cxd4 builds the big centre. Meet ...Bb4+ with Bd2 or Nc3.',
      'h6 d4 exd4 cxd4 Bb4+': "6...Bb4+ checks. 7.Bd2 offers to trade off Black's most active piece.",
      'h6 d4 exd4 cxd4 Bb4+ Bd2': '7.Bd2 blocks the check and challenges the bishop. Black usually trades on d2.',
      'h6 d4 exd4 cxd4 Bb4+ Bd2 Bxd2+': '7...Bxd2+ trades. 8.Nbxd2 develops and guards e4; 8.Qxd2 is fine too.',
      d6: '4...d6 props up e5 and frees the c8 bishop. 5.d4 still hits the bishop and e5.',
      'd6 d4': '5.d4 opens the centre with gain of time. After 5...exd4 6.cxd4 you keep two centre pawns.',
      'd6 d4 exd4': '5...exd4 gives up the centre. Retake with the c-pawn to keep pawns on d4 and e4.',
      'd6 d4 exd4 cxd4': '6.cxd4 completes your centre. The bishop goes to b6 or checks on b4; d5 can gain more space.',
      'd6 d4 exd4 cxd4 Bb6': '6...Bb6 keeps the bishop aimed at d4 and f2. Develop with Nc3 and castle; d5 can kick the c6 knight.',
      'd6 d4 exd4 cxd4 Bb4+': '6...Bb4+ checks. Block with Nc3 or Bd2 and finish developing; your centre is the trump.',
    },
  },
  {
    id: 'giuoco-pianissimo',
    name: 'Giuoco Pianissimo',
    lines: [`${IT} Bc5 d3`],
    plan: '4.d3 keeps e4 solid and avoids early fights. Castle, then c3, Re1 and Bb3; play d4 when everything is ready.',
    notes: {
      Nf6: '4...Nf6 develops and hits e4, which d3 already guards. Black can castle next.',
      'Nf6 O-O': '5.O-O puts your king safe and readies Re1. c3 and h3 often come next.',
      'Nf6 O-O d6': '5...d6 supports e5 and opens the c8 bishop, which may pin your knight from g4. h3 rules that out.',
      'Nf6 O-O O-O': '5...O-O: both kings are safe. Play c3 and Re1, or h3 to keep the bishop off g4.',
      'Nf6 c3': '5.c3 prepares d4 and gives your bishop a retreat on c2 later.',
      'Nf6 Nc3': '5.Nc3 develops toward d5. With d3 played, ...Nxe4 tricks no longer work.',
      'Nf6 Bg5': '5.Bg5 pins the f6 knight to the queen. Expect ...h6; keep the pin with Bh4 or take on f6.',
      'Nf6 Be3': "5.Be3 offers to trade Black's strong c5 bishop. If ...Bxe3 fxe3, the f-file opens for your rook.",
      'Nf6 Ng5': '5.Ng5 hits f7 again. Black covers it with 5...O-O, and the knight often has to return.',
      'Nf6 h3': "5.h3 keeps Black's bishop off g4, so your knight cannot be pinned.",
      d6: '4...d6 holds e5 and opens the c8 bishop. Same slow fight: castle, c3 and h3.',
      h6: '4...h6 rules out Ng5 and Bg5. Use the time for c3 and a later d4.',
    },
  },
  {
    id: 'giuoco-piano-castles',
    name: 'Giuoco Piano: 4.O-O',
    lines: [`${IT} Bc5 O-O`],
    plan: '4.O-O puts your king safe first. Next comes c3 and d4 for the centre, or d3 for the slow Pianissimo set-up.',
    notes: {
      Nf6: '4...Nf6 attacks e4. Defend it calmly with 5.d3.',
      'Nf6 d3': '5.d3 guards e4 for good. c3, Re1 and Nbd2 follow, with d4 later.',
      'Nf6 d4': '5.d4 opens lines while your king is already safe, usually at the cost of a pawn.',
      d6: '4...d6 holds e5 and readies ...Bg4 to pin your knight. c3 and d4, or h3 first.',
      'd6 c3': '5.c3 prepares d4. If Black pins with ...Bg4, h3 asks the bishop to decide.',
      'd6 c3 Bg4': '5...Bg4 pins your knight. After h3, ...Bxf3 Qxf3 gives you the bishop pair.',
      'd6 d3': '5.d3 keeps everything protected. Watch for ...Bg4; h3 keeps the bishop out.',
      h6: '4...h6 stops Ng5 and Bg5. Use the time: c3 and d4 build the centre.',
      'h6 c3': '5.c3 prepares d4 with gain of time on the c5 bishop.',
      'h6 c3 Nf6': '5...Nf6 hits e4. 6.d4 is the point: after 6...exd4 7.cxd4 the bishop must move.',
      'h6 c3 Nf6 d4': '6.d4 hits the bishop and e5. Your king is castled, so the centre can open.',
      'h6 c3 Nf6 d4 exd4': '6...exd4 gives up the centre. 7.cxd4 builds pawns on e4 and d4.',
      'h6 c3 Nf6 d4 exd4 cxd4': "7.cxd4 completes your centre. Next e5 or d5 can kick Black's knights.",
      'h6 c3 Nf6 d4 exd4 cxd4 Bb4': '7...Bb4 is no check, as your king has castled. 8.e5 kicks the f6 knight and gains space.',
      'h6 c3 Nf6 d4 exd4 cxd4 Bb6': '7...Bb6 keeps the bishop on the a7-g1 diagonal. Play e5 or Nc3: your centre is the trump.',
    },
  },
  {
    id: 'evans-gambit',
    name: 'Evans Gambit',
    lines: [`${IT} Bc5 b4`],
    plan: '4.b4 offers a pawn to deflect the bishop. After ...Bxb4, c3 and d4 gain time on it and build a big centre.',
    notes: {
      Bxb4: '4...Bxb4 accepts. 5.c3 hits the bishop and prepares d4.',
      'Bxb4 c3': '5.c3 kicks the bishop and readies d4. Black usually retreats to a5, still eyeing c3.',
      'Bxb4 c3 Ba5': '5...Ba5 is the main retreat. 6.d4: your centre and lead in development pay for the pawn.',
      'Bxb4 c3 Ba5 d4': '6.d4 opens lines while Black is uncastled. Castle next and bring the queen to b3 against f7.',
      'Bxb4 c3 Be7': '5...Be7 is a safe retreat. 6.d4 keeps building with gain of time.',
      Bb6: '4...Bb6 declines the pawn. 5.a4 threatens a5 against the bishop and wins queenside space.',
      'Bb6 c3': '5.c3 prepares d4. Your b4 pawn already gains queenside space.',
      'Bb6 c3 d6': '5...d6 holds e5. a4 and a5 can harass the bishop on b6.',
    },
  },
  {
    id: 'giuoco-piano-d4',
    name: 'Giuoco Piano: 4.d4',
    lines: [`${IT} Bc5 d4`],
    plan: '4.d4 opens the centre early, often as a gambit. After 4...exd4, c3 or O-O speeds up your development.',
    notes: {
      exd4: '4...exd4 takes. 5.c3 offers a second pawn for a big lead; 5.O-O keeps it simpler.',
      'exd4 c3': '5.c3 gambits a pawn: if ...dxc3, Nxc3 develops with a lead and open lines.',
      'exd4 O-O': '5.O-O gets your king safe first; c3 or Nxd4 can follow.',
    },
  },
  {
    id: 'italian-four-knights',
    name: 'Italian Four Knights',
    lines: [`${IT} Bc5 Nc3`],
    plan: 'Your knight guards e4 and eyes d5. Play d3 early: until then, ...Nxe4 and ...d5 can win the piece back with a fork.',
    notes: {
      Nf6: '4...Nf6 completes the four knights. 5.d3 stops ...Nxe4 tricks for good.',
      'Nf6 d3': '5.d3 shores up e4. Next Bg5, Be3 or O-O; Nd5 can trade off the f6 knight.',
      'Nf6 d3 d6': '5...d6 mirrors you. Bg5 pins the f6 knight; Black may answer ...Na5 to trade your bishop.',
      'Nf6 d3 d6 Bg5': "6.Bg5 pins the knight. ...h6 and ...g5 break the pin but loosen Black's king.",
      'Nf6 d3 h6': "5...h6 stops Bg5. Be3 offers to trade Black's strong bishop.",
      'Nf6 O-O': '5.O-O allows the fork trick 5...Nxe4 6.Nxe4 d5. 5.d3 avoids it.',
      d6: '4...d6 holds e5 and readies ...Bg4 or ...Nf6. d3 and h3 keep things safe.',
      'd6 d3': "5.d3 supports e4. Black's ...Bg4 pin is the move to watch; h3 asks the question.",
      'd6 d3 Bg4': '5...Bg4 pins your knight. h3 forces a choice: ...Bxf3 gives you the bishop pair, ...Bh5 keeps the pin.',
      'd6 d3 Nf6': '5...Nf6 completes development. Castle, or pin the knight with Bg5.',
    },
  },
  {
    id: 'two-knights',
    name: 'Two Knights Defence',
    lines: [`${IT} Nf6`],
    plan: '3...Nf6 hits e4 and invites 4.Ng5 against f7. Choose: 4.d3 keeps it calm, 4.Ng5 attacks, 4.d4 opens the centre.',
    notes: {},
  },
  {
    id: 'two-knights-d3',
    name: 'Two Knights: 4.d3',
    lines: [`${IT} Nf6 d3`],
    plan: '4.d3 guards e4 and keeps the game slow: c3, O-O, Re1 and Bb3, then d4. It often becomes a Giuoco Pianissimo.',
    notes: {
      Bc5: "4...Bc5 transposes to the Giuoco Pianissimo: both bishops aim at the other side's f-pawn.",
      Be7: '4...Be7 is solid: Black castles and may push ...d5 later. Castle, then c3 and Re1.',
      h6: '4...h6 stops Ng5 and Bg5. Continue with c3, O-O and Re1; d4 comes later.',
      d6: '4...d6 guards e5 and frees the c8 bishop. Castle and prepare c3 and d4.',
      d5: '4...d5 opens the centre. After 5.exd5 Nxd5 the knight is strong, but e5 needs guarding.',
      'd5 exd5': '5.exd5 trades a centre pawn. Black takes back with the knight; Re1 will then press on e5.',
      'd5 exd5 Nxd5': '5...Nxd5 centralises the knight. Castle and play Re1 to hit e5; Nc3 can challenge d5.',
      'd5 exd5 Nxd5 O-O': '6.O-O gets your king safe. Re1 next piles on e5.',
      'd5 exd5 Nxd5 O-O Be7': '6...Be7 prepares to castle. Re1 hits e5, and the d5 knight may need ...Be6 for support.',
      'Bb4+': '4...Bb4+ checks to provoke c3. Play 5.c3, which you wanted anyway; b4 can then chase the bishop.',
    },
  },
  {
    id: 'two-knights-ng5',
    name: 'Two Knights: 4.Ng5',
    lines: [`${IT} Nf6 Ng5`],
    plan: '4.Ng5 hits f7 twice. After 4...d5 5.exd5 Na5 you can keep an extra pawn, but Black gets fast development.',
    notes: {
      d5: "4...d5 blocks your bishop's line to f7 and strikes at e4. Take with 5.exd5.",
      'd5 exd5': '5.exd5 reopens the line to f7. 5...Na5 is best; 5...Nxd5 allows a dangerous attack.',
      'd5 exd5 Na5': '5...Na5 hits your bishop and gives up a pawn for time. 6.Bb5+ keeps the bishop active.',
      'd5 exd5 Na5 Bb5+': '6.Bb5+ checks. After 6...c6 7.dxc6 bxc6 you are a pawn up; Black gets open lines.',
      'd5 exd5 Na5 Bb5+ c6': '6...c6 blocks and hits the bishop. Take with 7.dxc6, then drop the bishop back to e2 or d3.',
      'd5 exd5 Na5 Bb5+ c6 dxc6': "7.dxc6 bxc6 leaves you a pawn up. Black's lead in development is the compensation.",
      'd5 exd5 Na5 Bb5+ c6 dxc6 bxc6': '7...bxc6 attacks your bishop. Retreat to e2, the main line, or d3, and bring the g5 knight back soon.',
      'd5 exd5 Na5 Bb5+ c6 dxc6 bxc6 Be2': '8.Be2 is the main line. Black plays 8...h6, chasing your knight back to f3.',
      'd5 exd5 Na5 Bb5+ c6 dxc6 bxc6 Bd3': '8.Bd3 keeps the bishop near your king. Black has ...h6 or ...Nd5; castle soon.',
      'd5 exd5 Na5 Bb5+ c6 dxc6 bxc6 Qf3': '8.Qf3 attacks c6, which is pinned to the a8 rook. Black hits back with ...Rb8 or ...e4.',
      'd5 exd5 Na5 Bb5+ Bd7': '6...Bd7 blocks with a piece. 7.Qe2 defends the bishop and presses e5.',
      'd5 exd5 Na5 Bb5+ Bd7 Qe2': '7.Qe2 holds b5 and eyes e5. Black trades with ...Bxb5 or develops with ...Bd6.',
      'd5 exd5 Nxd5': '5...Nxd5 is a mistake. 6.d4 opens lines; 6.Nxf7, the Fried Liver, drags the king out.',
      'd5 exd5 Nxd5 Nxf7': '6.Nxf7 is the Fried Liver: a knight for a pawn to pull the king to f7.',
      'd5 exd5 Nxd5 Nxf7 Kxf7': '6...Kxf7 takes. 7.Qf3+ hits the king and the d5 knight, pinned by your bishop on c4.',
      'd5 exd5 Nxd5 Nxf7 Kxf7 Qf3+': '7.Qf3+ forces the king forward: 7...Ke6 holds d5. Other king moves let you take on d5.',
      'd5 exd5 Nxd5 Nxf7 Kxf7 Qf3+ Ke6': '7...Ke6 guards the knight with the king. 8.Nc3 attacks d5 a third time.',
      'd5 exd5 Nxd5 Nxf7 Kxf7 Qf3+ Ke6 Nc3': "8.Nc3 piles on d5. Black's king is stuck in the centre; d4 next opens more lines.",
      'd5 exd5 Nxd5 Nxf7 Kxf7 Qf3+ Ke8': "7...Ke8 gives up d5: 8.Bxd5 leaves you a pawn up, and Black's king has lost castling.",
      'd5 exd5 Nxd5 d4': '6.d4 opens the centre and keeps the pressure on f7 and d5. Your pieces arrive first.',
      'd5 exd5 b5': '5...b5 offers a pawn to deflect your bishop. 6.Bf1 hits b5 and keeps the pawn on d5.',
      Bc5: '4...Bc5 is the Traxler: Black ignores f7 and hits f2. 5.Bxf7+ is the safe capture; 5.Nxf7 gets wild.',
      'Bc5 Bxf7+': "5.Bxf7+ grabs the pawn with check. Black's king must move and can no longer castle.",
      'Bc5 Nxf7': '5.Nxf7 forks queen and rook, but 5...Bxf2+ drags your king into the open.',
      'Bc5 Nxf7 Bxf2+': '5...Bxf2+ is the point. 6.Kxf2 Nxe4+ exposes your king; 6.Kf1 avoids the knight check.',
      Nxe4: "4...Nxe4 grabs a pawn but drops f7. 5.Bxf7+ Ke7 leaves Black's king stuck in the centre.",
      'Nxe4 Bxf7+': '5.Bxf7+ forces 5...Ke7: Black can never castle, and d3 will hit the e4 knight.',
      'Nxe4 Bxf7+ Ke7': "5...Ke7 is forced. 6.d3 attacks the e4 knight; Black's king will not find safety soon.",
    },
  },
  {
    id: 'two-knights-d4',
    name: 'Two Knights: 4.d4',
    lines: [`${IT} Nf6 d4`],
    plan: '4.d4 opens the centre at once. After 4...exd4, castle or push e5 and use your lead in development.',
    notes: {
      exd4: '4...exd4 takes. 5.O-O is the main move; 5.e5 kicks the knight, and 5...d5 hits back.',
      'exd4 O-O': "5.O-O ignores the pawn: if 5...Nxe4, 6.Re1 pins the knight to Black's king.",
      'exd4 O-O Nxe4': '5...Nxe4 grabs a pawn. 6.Re1 pins it; after 6...d5 7.Bxd5 Qxd5 8.Nc3 you win the piece back.',
      'exd4 O-O Nxe4 Re1': '6.Re1 pins the knight. 6...d5 defends it, but 7.Bxd5 Qxd5 8.Nc3 hits queen and knight.',
      'exd4 O-O Nxe4 Re1 d5': '6...d5 props up the knight. 7.Bxd5 Qxd5 8.Nc3 wins the material back.',
      'exd4 O-O Nxe4 Re1 d5 Bxd5': '7.Bxd5 deflects the queen. After 7...Qxd5 8.Nc3 attacks the queen and the pinned knight.',
      'exd4 O-O Nxe4 Re1 d5 Bxd5 Qxd5': '7...Qxd5 takes. 8.Nc3 hits the queen, and Nxe4 next regains the piece.',
      'exd4 O-O Nxe4 Re1 d5 Bxd5 Qxd5 Nc3': '8.Nc3 attacks queen and knight. The queen moves, and you take on e4.',
      'exd4 O-O d6': '5...d6 keeps the extra pawn quietly. Take back with Nxd4 and enjoy your space.',
      'exd4 O-O Be7': '5...Be7 prepares to castle. 6.e5 drives the f6 knight away; then win back d4.',
      'exd4 e5': '5.e5 kicks the knight. 5...d5 is the right answer: it hits your bishop.',
      d6: '4...d6 holds e5. If 5.dxe5 dxe5 6.Qxd8+, ...Kxd8 loses castling and ...Nxd8 drops e5.',
      Nxe4: '4...Nxe4 grabs a pawn but leaves the knight loose. Hit back at once with 5.dxe5, 5.d5 or 5.Bd5.',
      'Nxe4 dxe5': '5.dxe5 gains space and threatens 6.Qd5, hitting the e4 knight and mate on f7.',
    },
  },
  {
    id: 'two-knights-nc3',
    name: 'Two Knights: 4.Nc3',
    lines: [`${IT} Nf6 Nc3`],
    plan: '4.Nc3 guards e4, but allows the fork trick 4...Nxe4 5.Nxe4 d5. After 4...Bc5, play d3 and develop calmly.',
    notes: {
      Bc5: '4...Bc5 makes it the Italian Four Knights. 5.d3 stops ...Nxe4 tricks for good.',
      Nxe4: '4...Nxe4 is the fork trick: after 5.Nxe4 d5, Black forks bishop and knight and wins the piece back.',
      'Nxe4 Nxe4': '5.Nxe4 takes the knight. 5...d5 now forks your bishop on c4 and knight on e4.',
      'Nxe4 Nxe4 d5': '5...d5 forks. Save the bishop with 6.Bd3; Black regains the piece and gets a free centre.',
      'Nxe4 Nxe4 d5 Bd3': '6.Bd3 saves the bishop near your king. After 6...dxe4 7.Bxe4 material is level.',
      'Nxe4 Nxe4 d5 Bd3 dxe4': '6...dxe4 regains the piece and hits your bishop. 7.Bxe4 wins the pawn back.',
      'Nxe4 Nxe4 d5 Bd3 dxe4 Bxe4': '7.Bxe4 restores material. Castle and play d3 or c3 with d4; Black is free and easy.',
      d5: '4...d5 opens the centre early. Take with 5.exd5: your bishop and knight then hit d5 together.',
      'd5 exd5': '5.exd5 wins a pawn for now. If 5...Nxd5, your c3 knight and bishop both hit the knight.',
      'd5 exd5 Nd4': '5...Nd4 centralises the knight instead of taking back. You keep the extra pawn; develop and castle.',
    },
  },
  {
    id: 'two-knights-castles',
    name: 'Two Knights: 4.O-O',
    lines: [`${IT} Nf6 O-O`],
    plan: '4.O-O gets your king safe first. 4...Bc5 leads to a normal Italian; after 4...Nxe4, 5.Re1 wins the pawn back.',
    notes: {
      Bc5: '4...Bc5 gives a Giuoco Piano with you already castled. d3, or c3 and d4, are the plans.',
      'Bc5 Nc3': '5.Nc3 allows the fork trick 5...Nxe4 6.Nxe4 d5. d3 first is safer.',
      'Bc5 Ng5': '5.Ng5 hits f7 again, but Black is well developed: 5...O-O or 5...d5 meets it.',
      Nxe4: '4...Nxe4 grabs the pawn. 5.Re1 attacks the knight, and you regain the pawn.',
    },
  },
  {
    id: 'hungarian',
    name: 'Hungarian Defence',
    lines: [`${IT} Be7`],
    plan: '3...Be7 is solid but passive: Black avoids a fight over f7. Take space with d4, castle, and use your freer pieces.',
    notes: {
      d4: '4.d4 claims the centre at once. Black must give it up with ...exd4 or hold with ...d6.',
      'd4 exd4': '4...exd4 hands you the centre. 5.Nxd4 takes back; 5.c3 is a gambit.',
      'd4 exd4 Nxd4': '5.Nxd4 recaptures with a centralised knight. Castle next; Black is solid but cramped.',
      'd4 d6': '4...d6 holds e5. 5.d5 gains space and pushes the c6 knight back.',
      d3: '4.d3 keeps it slow. Castle, then c3 and d4.',
      'O-O': '4.O-O keeps the choice of d4 or d3. Black continues ...Nf6 and ...O-O.',
    },
  },
  {
    id: 'anti-fried-liver',
    name: 'Anti-Fried Liver Defence',
    lines: [`${IT} h6`],
    plan: '3...h6 stops Ng5 for good but spends a move. Use it: c3 and d4 for the centre, or castle first and then d4.',
    notes: {
      'O-O': '4.O-O gets your king safe. c3 and d4 can follow, since ...h6 cost Black time.',
      'O-O Nf6': '4...Nf6 attacks e4. Re1 or Nc3 defends it; d3 is the quiet way.',
      'O-O Bc5': '4...Bc5 gives a Giuoco Piano where ...h6 is already played. c3 and d4 are strong now.',
      d4: "4.d4 hits e5 at once, before Black's pieces are out.",
      'd4 exd4': '4...exd4 gives up the centre. 5.Nxd4 recaptures with a strong central knight.',
      c3: "4.c3 prepares d4. Black's ...h6 did nothing to stop it.",
      'c3 Nf6': '4...Nf6 attacks e4. 5.d3 keeps it solid; 5.d4 is more ambitious.',
      'c3 d6': '4...d6 holds e5. d4 still comes; h3 first keeps the bishop off g4.',
      d3: '4.d3 keeps things slow. Castle, c3 and d4 later.',
      Nc3: '4.Nc3 develops and guards e4. d3 and Be3 can follow.',
    },
  },
  {
    id: 'paris-defence',
    name: 'Paris Defence',
    lines: [`${IT} d6`],
    plan: '3...d6 holds e5 but blocks the f8 bishop. Aim for c3 and d4; if Black pins with ...Bg4, h3 asks it to decide.',
    notes: {
      Nc3: '4.Nc3 develops and eyes d5. Watch for ...Bg4 pinning your knight.',
      'Nc3 Bg4': "4...Bg4 pins your knight. 5.h3: if 5...Bh5, 6.Nxe5 wins a pawn, as ...Bxd1 runs into Legal's mate.",
      'Nc3 Bg4 h3': '5.h3 asks the bishop: take on f3 and give you the bishop pair, or retreat to h5.',
      'Nc3 Bg4 h3 Bxf3': '5...Bxf3 gives up the bishop pair. 6.Qxf3 develops your queen with an eye on f7.',
      c3: '4.c3 prepares d4 for a big centre.',
      d3: '4.d3 keeps things calm. Watch for ...Be6 offering a trade of your strong bishop.',
      'd3 Be6': '4...Be6 challenges your bishop. Bxe6 fxe6 gives Black doubled pawns but an open f-file.',
      d4: '4.d4 opens the centre. After 4...exd4 5.Nxd4 your pieces become very active.',
    },
  },
  {
    id: 'blackburne-shilling',
    name: 'Blackburne Shilling Gambit',
    lines: [`${IT} Nd4`],
    plan: '3...Nd4 sets a trap: 4.Nxe5? Qg5 hits the knight and g2. Trade with 4.Nxd4 exd4, then castle and play c3.',
    notes: {
      Nxd4: '4.Nxd4 trades knights and avoids the trap. After 4...exd4, castle and play c3 to challenge d4.',
      'Nxd4 exd4': '4...exd4 leaves Black a pawn on d4. Castle and play c3 to break it up.',
      'Nxd4 exd4 Qf3': '5.Qf3 threatens Qxf7 mate. Black blocks with 5...Nf6 or 5...Qf6.',
      Nxe5: '4.Nxe5 walks into the trap: 4...Qg5 attacks the knight and g2 at once.',
      'Nxe5 Qg5': '4...Qg5 hits e5 and g2. Never take f7: 5.Nxf7 Qxg2 6.Rf1 Qxe4+ 7.Be2 Nf3 is mate.',
      'O-O': '4.O-O ignores the knight. ...Nxf3+ Qxf3 only helps your development.',
      c3: '4.c3 kicks the knight. If 4...Nxf3+ 5.Qxf3, your queen joins the game.',
    },
  },
  {
    id: 'rousseau-gambit',
    name: 'Rousseau Gambit',
    lines: [`${IT} f5`],
    plan: "3...f5 hits e4 but opens the diagonal to Black's king. Strike with 4.d4 while Black is behind in development.",
    notes: {
      d4: '4.d4 hits e5 and opens lines toward the weakened king.',
      'd4 exd4': '4...exd4 opens the centre. 5.Nxd4 recaptures with a strong central knight.',
      d3: '4.d3 keeps e4 safe. Ng5 can then aim at e6, weakened by ...f5.',
    },
  },
];

const CARO_KANN: Family[] = [
  {
    id: 'caro-kann',
    name: 'Caro-Kann Defence',
    lines: [''],
    plan: null,
    notes: {
      [CK]: '1...c6 prepares ...d5. If White takes on d5, you recapture with the c-pawn and keep a pawn in the centre.',
      [`${CK} d4`]: '2.d4 builds the ideal centre. Strike at it now with 2...d5.',
      [`${CK} d4 d5`]: '2...d5 hits e4. White must defend it with Nc3, Nd2 or f3, push past with e5, or exchange on d5.',
      [`${CK} d4 d5 Nc3`]: "3.Nc3 defends e4 with a piece. 3...dxe4 trades off White's centre pawn for free development.",
      [`${CK} d4 d5 Nd2`]: '3.Nd2 defends e4 and keeps c3 free for a pawn. 3...dxe4 4.Nxe4 leads to the same positions as 3.Nc3.',
      [`${CK} d4 d5 Nc3 dxe4`]: '3...dxe4 gives up the centre on purpose: you get easy development and no weaknesses.',
      [`${CK} d4 d5 Nd2 dxe4`]: '3...dxe4 gives up the centre for easy development. White takes back with the knight.',
      [`${CK} d4 d5 exd5`]: '3.exd5 releases the tension. Recapture with 3...cxd5 to keep a pawn on d5.',
      [`${CK} Qf3`]: '2.Qf3 brings the queen out early. 2...d5 hits e4, and ...Nf6 can later gain time on the queen.',
      [`${CK} Qf3 d5`]: '2...d5 hits e4. If 3.exd5 cxd5, your pawn on d5 controls the centre.',
      [`${CK} Qh5`]: '2.Qh5 is premature. 2...d5 strikes the centre, and ...Nf6 will gain time on the queen.',
      [`${CK} Qh5 d5`]: '2...d5 hits e4. If 3.exd5 cxd5, ...Nf6 develops with gain of time.',
      [`${CK} f4`]: '2.f4 grabs kingside space. 2...d5 hits e4 straight away.',
      [`${CK} f4 d5`]: '2...d5 hits e4. If 3.exd5 cxd5, develop with ...Nc6, ...Nf6 and ...Bg4.',
    },
  },
  {
    id: 'caro-kann-main-line',
    name: 'Main Line',
    lines: [CK_MAIN],
    plan: 'The e4 knight is centralised, but you have no weaknesses. Choose your set-up: 4...Bf5, 4...Nd7 or 4...Nf6.',
    notes: {},
  },
  {
    id: 'caro-kann-classical',
    name: 'Classical Variation',
    lines: [`${CK_MAIN} Bf5`],
    plan: '4...Bf5 gets your bishop out before ...e6. Expect Ng3 and h4: answer with ...Bg6, ...h6, ...Nd7 and ...e6.',
    notes: {
      Ng3: '5.Ng3 hits your bishop. Drop back with 5...Bg6, keeping it on the h7-b1 diagonal.',
      'Ng3 Bg6': '5...Bg6 keeps the bishop active. White often pushes h4 and h5 to chase it.',
      'Ng3 Bg6 h4': '6.h4 threatens h5, hitting your bishop. Play 6...h6 so the bishop can drop to h7.',
      'Ng3 Bg6 h4 h6': '6...h6 makes room on h7. After h5 the bishop retreats there and stays on the long diagonal.',
      'Ng3 Bg6 h4 h6 Nf3': '7.Nf3 develops. 7...Nd7 stops Ne5 and prepares ...Ngf6.',
      'Ng3 Bg6 h4 h6 Nf3 Nd7': '7...Nd7 guards e5. White often plays 8.h5 Bh7 9.Bd3, offering a bishop trade.',
      'Ng3 Bg6 Nf3': "6.Nf3 develops. 6...Nd7 keeps White's knight off e5.",
      'Ng3 Bg6 Nf3 Nd7': '6...Nd7 guards e5. Next ...Ngf6 and ...e6 finish a solid set-up.',
      'Ng3 Bg6 Nf3 e6': "6...e6 frees your dark-squared bishop. If Bd3, trading on d3 removes White's best attacker.",
      'Ng3 Bg6 f4': '6.f4 threatens f5, hitting the bishop. 6...e6 is the answer: f5 can then be met by ...exf5.',
      Nc3: '5.Nc3 avoids the trade of pieces. Continue ...e6, ...Nf6 and ...Nd7.',
      Bd3: '5.Bd3 offers a trade of light-squared bishops. Trading is fine for you: it removes a key attacker.',
    },
  },
  {
    id: 'caro-kann-karpov',
    name: 'Karpov Variation',
    lines: [`${CK_MAIN} Nd7`],
    plan: '4...Nd7 prepares ...Ngf6, so a trade on f6 is met by the knight and your pawns stay healthy. Then ...e6 or ...Bf5.',
    notes: {
      Nf3: '5.Nf3 develops. 5...Ngf6 challenges the e4 knight; take back with the knight if White trades.',
      'Nf3 Ngf6': '5...Ngf6 offers the trade. After Nxf6+ Nxf6 your structure is perfect.',
      Qe2: '5.Qe2 sets a trap: 5...Ngf6?? 6.Nd6 is smothered mate. Play 5...Ndf6 instead.',
      Bc4: '5.Bc4 eyes f7. Play 5...Ngf6; if Ng5, ...e6 shuts the bishop out.',
      Ng5: '5.Ng5 eyes f7 and e6. 5...Ngf6 6.Bd3 e6 is the solid answer.',
    },
  },
  {
    id: 'caro-kann-nf6',
    name: '4...Nf6 Variation',
    lines: [`${CK_MAIN} Nf6`],
    plan: '4...Nf6 challenges the e4 knight. After 5.Nxf6+, ...exf6 gives quick development, ...gxf6 an open g-file.',
    notes: {
      'Nxf6+': '5.Nxf6+ trades. 5...exf6 opens lines for your bishop and queen; 5...gxf6 is sharper.',
      'Nxf6+ exf6': '5...exf6 gives easy development: ...Bd6, ...O-O and ...Re8. White has the healthier pawns for an endgame.',
      'Nxf6+ gxf6': '5...gxf6 opens the g-file for your rook. Your king often stays in the centre or goes queenside.',
      Ng3: '5.Ng3 avoids the trade. Develop freely with ...e6, ...Bd6 or ...Bg4.',
      Ng5: '5.Ng5 eyes f7. ...h6 kicks it; then watch for a knight sacrifice on f7.',
    },
  },
  {
    id: 'caro-kann-advance',
    name: 'Advance Variation',
    lines: [CK_ADVANCE],
    plan: 'White grabs space with e5. Get your bishop out with ...Bf5 before ...e6, then hit the pawn chain with ...c5.',
    notes: {
      Bf5: '3...Bf5 develops the bishop outside the pawn chain before ...e6 shuts it in.',
      'Bf5 Nc3': '4.Nc3 prepares g4 to chase your bishop. Play 4...e6 and be ready for ...Bg6 and ...c5.',
      'Bf5 Nc3 e6': '4...e6 opens your other bishop. If g4, drop back to g6 and strike with ...c5.',
      'Bf5 Bd3': '4.Bd3 offers a bishop trade. 4...Bxd3 5.Qxd3 e6 is comfortable: you swap off your problem bishop.',
      'Bf5 c3': '4.c3 supports d4. Continue with ...e6, ...Nd7, ...Ne7 and ...c5.',
      'Bf5 h4': '4.h4 threatens g4 and h5 against the bishop. 4...h5 stops it, at the cost of the g5 square.',
      'Bf5 h4 h5': '4...h5 halts the h-pawn. White gets g5 for a piece, but your bishop stays free.',
      c5: '3...c5 hits d4 at once. It costs a tempo, but the chain is challenged before White is ready.',
      'c5 dxc5': '4.dxc5 gives up the base of the chain. ...e6 and ...Bxc5 win the pawn back with good development.',
      'c5 c3': '4.c3 supports d4. Develop with ...Nc6 and ...Bf5 or ...Bg4, pressing d4.',
      'c5 c4': '4.c4 hits d5. 4...cxd4 opens the position; ...Nc6 then gains time on the queen.',
      'c5 Nf3': '4.Nf3 supports d4. ...Bg4 pins the knight, and ...Nc6 adds pressure on d4.',
    },
  },
  {
    id: 'caro-kann-short',
    name: 'Advance: Short System',
    lines: [`${CK_ADVANCE} Bf5 Nf3`],
    plan: 'White plays Nf3, Be2, O-O and c3. Build with ...e6, ...c5, ...Nc6 and ...Ne7, and keep pressing d4.',
    notes: {
      e6: '4...e6 opens your dark-squared bishop; the light-squared one is already outside the chain.',
      'e6 Be2': '5.Be2 prepares O-O. Strike with 5...c5, or play ...Nd7 and ...Ne7 first.',
      'e6 Be2 c5': '5...c5 hits d4. White supports it with Be3 or c3; your knight joins with ...Nc6.',
      'e6 Bd3': '5.Bd3 offers a bishop trade. Take: after ...Bxd3 Qxd3 your remaining bishop is the good one.',
      'e6 c3': '5.c3 props up d4. Play ...c5 anyway, or ...Nd7 and ...Ne7 to prepare it.',
      'e6 Nc3': '5.Nc3 develops. ...c5 still hits d4, and ...Nc6 adds pressure.',
    },
  },
  {
    id: 'caro-kann-bayonet',
    name: 'Advance: Bayonet Attack',
    lines: [`${CK_ADVANCE} Bf5 Nc3 e6 g4`, `${CK_ADVANCE} Bf5 g4`],
    plan: 'White chases your bishop with g4 and h4. Tuck it away on g6 or d7, then hit the centre with ...c5.',
    notes: {
      Bg6: '5...Bg6 keeps the bishop on its diagonal. Next ...c5 hits d4 before the kingside storm lands.',
      'Bg6 Nge2': '6.Nge2 prepares h4 and Nf4. Strike now with 6...c5.',
    },
  },
  {
    id: 'caro-kann-exchange',
    name: 'Exchange Variation',
    lines: [`${CK} d4 d5 exd5 cxd5`],
    plan: 'Symmetrical pawns, so piece play decides. Develop ...Nc6, ...Nf6 and ...Bg4 or ...Bf5; later ...b5-b4 can hit c3.',
    notes: {
      Bd3: '4.Bd3 aims at h7 and keeps your bishop off f5 for now. Develop with ...Nc6 and ...Nf6; ...Bg4 works well.',
      'Bd3 Nc6': '4...Nc6 hits d4. White usually guards it with c3.',
      'Bd3 Nc6 c3': '5.c3 holds d4. Continue with ...Nf6 and ...Bg4, pinning the knight once it lands on f3.',
      'Bd3 Nf6': '4...Nf6 develops and guards h7. ...Nc6 and ...Bg4 come next.',
      'Bd3 e6': '4...e6 is solid but locks in your light-squared bishop. ...Bd6, ...Nf6 and ...O-O follow.',
      Nf3: '4.Nf3 develops. ...Nc6, ...Nf6 and ...Bg4 give you easy play.',
      Nc3: '4.Nc3 develops. ...Nf6 and ...Nc6 hit back at d4, then ...Bg4 or ...Bf5.',
      c3: '4.c3 supports d4 early. Develop freely: ...Nc6, ...Nf6 and ...Bf5.',
      Bf4: '4.Bf4 develops actively. ...Nc6 and ...Qb6 can hit d4 and b2.',
      'Bb5+': '4.Bb5+ checks. Block with ...Nc6 or ...Bd7; both develop.',
    },
  },
  {
    id: 'caro-kann-panov',
    name: 'Panov Attack',
    lines: [`${CK} d4 d5 exd5 cxd5 c4`],
    plan: 'White accepts an isolated d-pawn for activity. Blockade d5, develop ...Nf6, ...e6 and ...Nc6, and trade pieces.',
    notes: {
      Nf6: '4...Nf6 develops and adds a defender to d5. Next ...e6 or ...Nc6.',
      'Nf6 Nc3': '5.Nc3 piles on d5. Choose ...e6 for a solid game or ...Nc6 for active play.',
      'Nf6 Nc3 e6': '5...e6 shores up d5. Your dark-squared bishop goes to e7 or b4.',
      'Nf6 Nc3 Nc6': "5...Nc6 develops and hits d4, White's weak spot.",
      e6: '4...e6 shores up d5 and opens your dark-squared bishop.',
    },
  },
  {
    id: 'caro-kann-fantasy',
    name: 'Fantasy Variation',
    lines: [`${CK} d4 d5 f3`],
    plan: "3.f3 props up e4 but weakens White's king. Hit the centre: ...e6 and ...c5, or ...dxe4 and ...e5.",
    notes: {
      dxe4: "3...dxe4 4.fxe4 e5 hits d4 at once while White's king is airy.",
      'dxe4 fxe4': '4.fxe4 gives White a big centre. Hit it now with 4...e5.',
      'dxe4 fxe4 e5': '4...e5 strikes back at d4, and the open e1-h4 diagonal gives your queen ...Qh4+ ideas.',
      e6: '3...e6 prepares ...c5 to hit d4. If 4.Nc3, ...Bb4 pins the knight and pressures e4.',
      Qb6: "3...Qb6 hits d4 and b2 at once, while White's knight cannot use f3.",
    },
  },
  {
    id: 'caro-kann-two-knights',
    name: 'Two Knights Variation',
    lines: [`${CK} Nc3 d5 Nf3`],
    plan: 'Pin the f3 knight with ...Bg4. After h3, take it and build with ...e6 and ...Nf6: a rock-solid set-up.',
    notes: {
      Bg4: '3...Bg4 pins the f3 knight, which guards d4 and e5. h3 usually follows.',
      'Bg4 h3': '4.h3 asks the bishop. 4...Bxf3 5.Qxf3 e6 is rock solid; 4...Bh5 keeps the pin.',
      'Bg4 h3 Bxf3': '4...Bxf3 gives up the bishop pair but removes a key defender. Follow with ...e6 and ...Nf6.',
      'Bg4 h3 Bh5': '4...Bh5 keeps the pin. If g4, drop back to g6; your bishop stays active.',
      dxe4: '3...dxe4 takes the centre pawn. After 4.Nxe4, ...Bf5, ...Nd7 or ...Nf6 work like the main lines.',
      'dxe4 Nxe4': '4.Nxe4 recaptures. Develop as in the main line: ...Bf5 to hit the knight, or ...Nd7 and ...Ngf6.',
      'dxe4 Nxe4 Bf5': '4...Bf5 gains time on the knight. After Ng3 Bg6, continue ...e6 and ...Nf6.',
    },
  },
  {
    id: 'caro-kann-nf3',
    name: 'Caro-Kann: 2.Nf3',
    lines: [`${CK} Nf3`],
    plan: '2.Nf3 holds back the d-pawn. Play ...d5 anyway, then pin the knight with ...Bg4 when it helps.',
    notes: {
      d5: '2...d5 hits e4. White chooses between 3.Nc3, 3.e5, 3.exd5 and 3.d3.',
      'd5 exd5': '3.exd5 releases the tension. Take back 3...cxd5 for a pawn on d5 and an open c-file.',
      'd5 exd5 cxd5': '3...cxd5 gives you a solid centre pawn. Develop with ...Nc6, ...Nf6 and ...Bg4.',
      'd5 exd5 cxd5 d4': '4.d4 reaches an Exchange Variation. ...Nc6, ...Nf6 and ...Bg4 develop with pressure on d4.',
      'd5 exd5 cxd5 d4 Nf6': '4...Nf6 develops and covers d5 and h7 at once.',
      'd5 exd5 cxd5 d4 Nc6': '4...Nc6 hits d4. If Bb5 pins it, ...Bd7 or ...a6 breaks the pin.',
      'd5 exd5 cxd5 d4 Bg4': '4...Bg4 pins the knight that guards d4. ...Nc6 next adds pressure.',
      'd5 exd5 cxd5 Nc3': '4.Nc3 hits d5. ...Nf6 guards it; ...d4 kicks the knight and gains space.',
      'd5 exd5 cxd5 c4': '4.c4 hits d5, Panov style. ...Nf6 and ...e6 keep it solid.',
      'd5 e5': "3.e5 gains space. Without d4 played yet, 3...Bg4 pins the knight and weakens White's grip.",
      'd5 e5 Bg4': '3...Bg4 pins the knight that supports e5 and d4. Next ...e6 and ...c5 attack the chain.',
      'd5 e5 Bg4 d4': '4.d4 makes it an Advance with your bishop on g4. Play ...e6 and ...c5.',
      'd5 e5 Bg4 d4 e6': '4...e6 opens your other bishop. ...c5 comes next, and ...Bxf3 can remove a defender of d4.',
      'd5 e5 Bf5': '3...Bf5 develops outside the chain. ...e6 and ...c5 come next.',
      'd5 d3': '3.d3 supports e4 quietly. ...Bg4 is natural; 3...dxe4 4.dxe4 Qxd1+ swaps queens.',
      'd5 d3 dxe4': '3...dxe4 opens the d-file. 4.dxe4 allows a queen trade; 4.Ng5 is a gambit aimed at f7 and e4.',
      'd5 d3 dxe4 Ng5': '4.Ng5 gambits a pawn, eyeing e4 and f7. Develop with ...Nf6 and ...e6 and keep f7 covered.',
      'd5 d3 dxe4 dxe4': "4.dxe4 lets you swap queens with 4...Qxd1+, and White's king loses the right to castle.",
      'd5 d3 Bg4': '3...Bg4 pins the knight. ...e6, ...Nf6 and ...Nd7 give a solid set-up.',
    },
  },
  {
    id: 'caro-kann-hillbilly',
    name: 'Hillbilly Attack',
    lines: [`${CK} Bc4`],
    plan: '2...d5 hits the bishop and e4. After 3.exd5 cxd5 the bishop must move again, and you have a free centre.',
    notes: {
      d5: '2...d5 hits both the bishop and e4. White must take on d5 or move the bishop.',
      'd5 exd5': '3.exd5 trades. Recapture with 3...cxd5, hitting the bishop again.',
      'd5 exd5 cxd5': '3...cxd5 attacks the bishop and gives you a strong d5 pawn. It goes to b3 or checks on b5.',
      'd5 exd5 cxd5 Bb3': '4.Bb3 keeps the bishop aimed at d5 and f7. Develop with ...Nf6 and ...Nc6, then ...Bf5 or ...Bg4.',
      'd5 exd5 cxd5 Bb3 Nf6': '4...Nf6 develops and guards d5. Next ...Nc6 and ...Bf5 or ...Bg4.',
      'd5 exd5 cxd5 Bb3 Bf5': '4...Bf5 develops outside the pawn chain. If Qf3 hits f5 and d5, ...e6 covers both.',
      'd5 exd5 cxd5 Bb3 Nc6': '4...Nc6 develops and eyes d4 and e5. ...Nf6 and ...Bf5 or ...Bg4 follow.',
      'd5 exd5 cxd5 Bb3 e5': '4...e5 takes the whole centre with pawns on d5 and e5.',
      'd5 exd5 cxd5 Bb5+': '4.Bb5+ checks. ...Nc6 develops; ...Bd7 offers a bishop trade.',
      'd5 Bb3': '3.Bb3 leaves e4 hanging: 3...dxe4 wins a pawn. If 4.Qh5, guard f7 with ...e6 or ...g6.',
    },
  },
  {
    id: 'caro-kann-accelerated-panov',
    name: 'Accelerated Panov',
    lines: [`${CK} c4`],
    plan: '2.c4 hits d5 in advance. Play ...d5 anyway: after the trades on d5, ...Nf6 and ...Nxd5 win the pawn back.',
    notes: {
      d5: '2...d5 strikes at once. White can take with the e- or c-pawn; you will regain the pawn.',
      'd5 exd5': '3.exd5 trades. Take back 3...cxd5; if 4.cxd5, play 4...Nf6 and ...Nxd5.',
      'd5 exd5 cxd5': '3...cxd5 hits c4. If 4.cxd5, 4...Nf6 regains the pawn without bringing your queen out early.',
      'd5 exd5 cxd5 cxd5': '4.cxd5 leaves White a pawn up for now. 4...Nf6 wins it back; 4...Qxd5 lets Nc3 gain time.',
      'd5 exd5 cxd5 cxd5 Nf6': '4...Nf6 attacks d5. White defends with Nc3 or Bb5+, but ...Nxd5 comes soon.',
      'd5 exd5 cxd5 cxd5 Qxd5': '4...Qxd5 regains the pawn, but 5.Nc3 hits the queen and gains time.',
      'd5 exd5 cxd5 cxd5 Qxd5 Nc3': '5.Nc3 hits the queen. Drop it back to d8 or a5 and develop quickly.',
      'd5 cxd5': '3.cxd5 trades. Take back 3...cxd5; after 4.exd5, ...Nf6 regains the pawn.',
      'd5 cxd5 cxd5': '3...cxd5 hits e4. White takes with exd5 or pushes e5.',
      'd5 cxd5 cxd5 exd5': '4.exd5 leaves White a pawn up for now. 4...Nf6 wins it back; 4...Qxd5 lets Nc3 gain time.',
      'd5 cxd5 cxd5 e5': '4.e5 gains space, Advance style. Develop with ...Nc6 and ...Bf5 and hit d4.',
    },
  },
  {
    id: 'caro-kann-d3',
    name: 'Caro-Kann: 2.d3',
    lines: [`${CK} d3`],
    plan: "2.d3 heads for a King's Indian Attack: Nd2, Ngf3, g3, Bg2 and O-O. Take space with ...d5 and ...e5.",
    notes: {
      d5: '2...d5 claims the centre. White is in no hurry, so you can build with ...e5 or ...Bg4.',
      'd5 exd5': '3.exd5 trades. Take back 3...cxd5 for a strong pawn on d5.',
      'd5 exd5 cxd5': '3...cxd5 gives you more of the centre than White. Develop with ...Nc6, ...Nf6 and ...Bg4.',
      'd5 Nd2': '3.Nd2 keeps e4 supported. 3...e5 stakes out the centre.',
      'd5 Nd2 e5': '3...e5 takes your share of the centre. ...Bd6, ...Nf6 and ...O-O follow.',
      'd5 Nc3': '3.Nc3 adds a defender to e4. 3...dxe4 4.Nxe4 gives a main-line type game; ...d4 gains space instead.',
      'd5 Nf3': '3.Nf3 develops. ...Bg4 pins it, or ...dxe4 offers a queen trade.',
    },
  },
  {
    id: 'caro-kann-nc3',
    name: 'Caro-Kann: 2.Nc3',
    lines: [`${CK} Nc3`],
    plan: "2.Nc3 guards e4 and keeps White's options open. After 2...d5, 3.d4 is the main line and 3.Nf3 the Two Knights.",
    notes: {
      d5: '2...d5 hits e4. White can defend with Nf3 or d4, take on d5, or play Qf3.',
      'd5 d4': '3.d4 transposes to the main line. 3...dxe4 4.Nxe4, then choose ...Bf5, ...Nd7 or ...Nf6.',
      'd5 exd5': '3.exd5 trades. Recapture 3...cxd5 to keep a strong pawn on d5.',
      'd5 exd5 cxd5': '3...cxd5 leaves you the extra centre pawn. Develop with ...Nf6, ...Nc6 and ...Bg4 or ...Bf5.',
      'd5 exd5 cxd5 d4': '4.d4 gives an Exchange set-up. ...Nf6, ...Nc6 and ...Bf5 or ...Bg4.',
      'd5 exd5 cxd5 Nf3': '4.Nf3 develops. ...Nc6, ...Nf6 and ...Bg4 give you easy play.',
      'd5 Qf3': '3.Qf3 defends e4 with the queen. ...d4 kicks the knight and gains space, or ...dxe4 and ...Nf6 hit the queen.',
      'd5 f3': '3.f3 holds e4 with a pawn. 3...d4 kicks the knight; ...e5 then grabs space.',
    },
  },
];

export const FAMILIES: Record<OpeningId, Family[]> = { italian: [KINGS_PAWN, ...ITALIAN], 'caro-kann': [KINGS_PAWN, ...CARO_KANN] };
