// The coach's notes on the opening moves, written to the user: White in the Italian, Black in the Caro-Kann.
import type { OpeningId } from '../content/types';

export interface Family {
  /** Stable id; also the id of the plan's note, so the store counts when the user met the family. */
  id: string;
  name: string;
  /** Moves from the initial position to the family's first position; extra lines are other move orders. */
  lines: string[];
  /** Shown where the family starts; null for the opening's trunk, which has no single plan. */
  plan: string | null;
  /** Why each move is played, keyed by the moves after the family's first line. */
  notes: Record<string, string>;
}

/** The id of a family's note on the moves `after` its first line; the plan's id is the family's own. */
export const moveNoteId = (family: Family, after: string) => `${family.id}:${after}`;

const IT = 'e4 e5 Nf3 Nc6 Bc4';
const CK = 'e4 c6';
const CK_MAIN = `${CK} d4 d5 Nc3 dxe4 Nxe4`;
const CK_ADVANCE = `${CK} d4 d5 e5`;

/** 1.e4 starts both openings, so its note suits either side. */
const KINGS_PAWN: Family = {
  id: 'kings-pawn',
  name: "King's Pawn Opening",
  lines: [''],
  plan: null,
  notes: { e4: '1.e4 takes the centre and opens lines for the queen and the light-squared bishop.' },
};

const ITALIAN: Family[] = [
  {
    id: 'italian',
    name: 'Italian Game',
    lines: [''],
    plan: null,
    notes: {
      'e4 e5': "1...e5 claims an equal share of the centre and frees Black's queen and dark-squared bishop.",
      'e4 e5 Nf3': '2.Nf3 develops with a threat: the knight attacks the pawn on e5.',
      'e4 e5 Nf3 Nc6': '2...Nc6 defends e5 with a developing move and keeps an eye on d4.',
      [IT]: "3.Bc4 aims the bishop at f7, the weakest square in Black's camp: only the king defends it.",
      [`${IT} f6`]: "3...f6 holds e5 but takes the knight's best square and weakens Black's king. Open lines with d4.",
      [`${IT} f6 O-O`]: "4.O-O gets your king safe first. d4 next opens lines toward Black's weakened king.",
    },
  },
  {
    id: 'giuoco-piano',
    name: 'Giuoco Piano',
    lines: [`${IT} Bc5`],
    plan: "3...Bc5 points Black's bishop at f2, as yours points at f7. Build the centre with c3 and d4, or play slowly with d3.",
    notes: {},
  },
  {
    id: 'giuoco-piano-c3',
    name: 'Giuoco Piano: 4.c3',
    lines: [`${IT} Bc5 c3`],
    plan: '4.c3 prepares d4, which hits the bishop and takes the centre. If Black takes on d4, recapture with the c-pawn.',
    notes: {
      Bb6: '4...Bb6 drops back before it is asked. 5.d4 takes the centre: after ...exd4 cxd4 your pawns stand side by side.',
      'Bb6 d4': '5.d4 attacks e5. If 5...exd4, 6.cxd4 gives you pawns on d4 and e4.',
      Nf6: "4...Nf6 attacks e4. Your pawn on c3 has taken the knight's square, so defend with d3 or strike with d4.",
      'Nf6 d3': '5.d3 keeps e4 solid and plays slowly: castle, Re1 and Nbd2, then d4 later. This is the Giuoco Pianissimo.',
      'Nf6 d3 O-O': "5...O-O tucks Black's king away. Castle too; both sides manoeuvre before d4 or ...d5.",
      'Nf6 d3 a6': '5...a6 gives the bishop a retreat on a7, safe from your d4 and b4.',
      'Nf6 d3 d5': '5...d5 is premature: after 6.exd5 Nxd5 7.Qb3, your queen and bishop pile up on d5 and f7.',
      'Nf6 d3 d6': '5...d6 supports e5 and frees the c8 bishop. Castle, then Re1, Nbd2 and h3 before d4.',
      'Nf6 d3 d6 O-O': '6.O-O tucks your king away. Next Re1, Nbd2 and Bb3; Black often saves the bishop with ...a6 and ...Ba7.',
      'Nf6 d3 d6 O-O Bg4': '6...Bg4 pins your knight to the queen. 7.h3 makes the bishop decide: take on f3 or step back.',
      'Nf6 d3 d6 O-O O-O h3': "7.h3 keeps Black's bishop off g4, so your f3 knight is never pinned to the queen. Re1 and Nbd2 follow.",
      'Nf6 d3 h6': '5...h6 stops Ng5 and Bg5. Castle and play Re1; Nbd2-f1-g3 is a typical regrouping.',
      'Nf6 d4': '5.d4 hits the bishop and e5 together. Black usually takes, and you recapture toward the centre.',
      'Nf6 d4 exd4': '5...exd4 releases the tension. 6.cxd4 builds your centre, but Black gets a check on b4.',
      'Nf6 d4 exd4 cxd4': '6.cxd4 hits the bishop and builds a big centre. Black checks on b4; a retreat lets d5 and e5 kick both knights.',
      'Nf6 d4 exd4 cxd4 Bb4+': '6...Bb4+ gains time with a check. 7.Bd2 is the safe block; 7.Nc3 offers the e4 pawn.',
      'Nf6 d4 exd4 cxd4 Bb4+ Bd2': '7.Bd2 blocks and offers to trade bishops. After ...Bxd2+ Nbxd2 your knight guards e4.',
      'Nf6 d4 exd4 cxd4 Bb4+ Bd2 Bxd2+': '7...Bxd2+ trades. Take back with the b1 knight so it covers e4; Black hits back with ...d5.',
      'Nf6 d4 exd4 cxd4 Bb4+ Bd2 Bxd2+ Nbxd2': '8.Nbxd2 guards e4. Expect 8...d5: after 9.exd5 Nxd5 10.Qb3 your pieces are active around d4.',
      'Nf6 d4 exd4 cxd4 Bb4+ Bd2 Bxd2+ Nbxd2 O-O': '8...O-O misses 8...d5. Now 9.d5 kicks the c6 knight, and your pawns control the centre.',
      'Nf6 d4 exd4 cxd4 Bb4+ Bd2 Nxe4': '7...Nxe4 grabs a pawn, but 8.Bxb4 Nxb4 9.Bxf7+ Kxf7 10.Qb3+ wins the knight on b4 back.',
      'Nf6 d4 exd4 cxd4 Bb4+ Bd2 Nxe4 Bxb4': '8.Bxb4 takes the bishop. Black must take back on b4, or stay a piece down.',
      'Nf6 d4 exd4 cxd4 Bb4+ Bd2 Nxe4 Bxb4 Nxb4': '8...Nxb4 recaptures, but the knight is loose. 9.Bxf7+ Kxf7 10.Qb3+ checks and wins it back.',
      'Nf6 d4 exd4 cxd4 Bb4+ Nc3': '7.Nc3 develops and offers e4. After 7...Nxe4 8.O-O you get open lines and a lead in development.',
      'Nf6 d4 exd4 cxd4 Bb4+ Nc3 Nxe4': '7...Nxe4 takes and piles up on your pinned c3 knight. 8.O-O breaks the pin.',
      'Nf6 d4 exd4 cxd4 Bb4+ Nc3 Nxe4 O-O': '8.O-O breaks the pin. 8...Bxc3 9.d5 is the Moller Attack: material for a fierce initiative.',
      'Nf6 d4 exd4 cxd4 Bb4+ Nc3 Nxe4 O-O Nxc3': "8...Nxc3 hits your queen. 9.bxc3 attacks the bishop; Black's best answer is 9...d5, hitting yours.",
      'Nf6 d4 exd4 e5': '6.e5 kicks the knight at once. Black hits back with 6...d5, attacking your bishop.',
      'Nf6 d4 exd4 e5 d5': '6...d5 hits your bishop. Drop it back to b5 or e2, then cxd4 wins back your pawn.',
      Qe7: '4...Qe7 adds a defender to e5, so Black can meet d4 with ...Bb6 and keep a pawn in the centre.',
      'Qe7 d4': '5.d4 claims the centre. Black holds e5 with 5...Bb6; castle and keep up the pressure.',
      Qf6: '4...Qf6 brings the queen out early and takes f6 from the knight. 5.d4 hits back in the centre.',
      'Qf6 d4': '5.d4 hits the bishop and e5. If 5...exd4, 6.e5 kicks the queen off f6.',
      'Qf6 d4 exd4': '5...exd4 takes. 6.e5 hits the queen first; you take back on d4 next move.',
      a6: '4...a6 makes room for the bishop on a7, but it is slow. 5.d4 hits the bishop and e5 at once.',
      'a6 d4': '5.d4 attacks the bishop and e5 together. If 5...exd4, retake with 6.cxd4 for two centre pawns.',
      'a6 d4 exd4': '5...exd4. Retake with 6.cxd4: the bishop is attacked again, and a7 is its best square.',
      'a6 d4 exd4 cxd4': "6.cxd4 attacks the bishop again. Black's best is 6...Ba7; then Nc3 and castling.",
      'a6 d4 exd4 cxd4 Bb4+': '6...Bb4+ checks. Block with 7.Nc3, a move that also brings out a piece.',
      'a6 d4 exd4 cxd4 Bb4+ Nc3': '7.Nc3 blocks with a developing move. Castle next, then d5 can kick the c6 knight.',
      d6: '4...d6 props up e5 and frees the c8 bishop. 5.d4 still hits the bishop and e5.',
      'd6 d4': '5.d4 opens the centre with gain of time. After 5...exd4 6.cxd4 you keep two centre pawns.',
      'd6 d4 exd4': '5...exd4 gives up the centre. Retake with the c-pawn to keep pawns on d4 and e4.',
      'd6 d4 exd4 cxd4': '6.cxd4 completes your centre. The bishop goes to b6 or checks on b4; d5 can gain more space.',
      'd6 d4 exd4 cxd4 Bb4+': '6...Bb4+ checks. Block with Nc3 or Bd2 and finish developing; your centre is the trump.',
      'd6 d4 exd4 cxd4 Bb4+ Bd2': '7.Bd2 offers to trade bishops and keeps your centre intact.',
      'd6 d4 exd4 cxd4 Bb4+ Bd2 Bxd2+': '7...Bxd2+ trades. Recapture with the knight or queen; you keep the big centre.',
      'd6 d4 exd4 cxd4 Bb4+ Bd2 Bxd2+ Nbxd2': '8.Nbxd2 takes back with a knight that now guards e4. Castle next; d5 can push the c6 knight back.',
      'd6 d4 exd4 cxd4 Bb4+ Nc3': '7.Nc3 blocks and develops. Castle soon to unpin the knight; d5 can gain space.',
      'd6 d4 exd4 cxd4 Bb4+ Nc3 Nf6': '7...Nf6 hits e4. Castle anyway: if ...Bxc3 bxc3 Nxe4, Re1 hits the knight and you are clearly better.',
      'd6 d4 exd4 cxd4 Bb4+ Nc3 Nf6 O-O': "8.O-O takes your king off the bishop's line, so the c3 knight guards e4 again.",
      'd6 d4 exd4 cxd4 Bb6': '6...Bb6 keeps the bishop aimed at d4 and f2. Develop with Nc3 and castle; d5 can kick the c6 knight.',
      h6: '4...h6 stops Ng5 and Bg5 but spends a move. Use it: 5.d4 hits the bishop and e5.',
      'h6 d4': '5.d4 hits the bishop and e5. After 5...exd4 6.cxd4 you have two pawns side by side in the centre.',
      'h6 d4 exd4': '5...exd4 opens the centre. Retake with 6.cxd4: the bishop must check on b4 or drop back.',
      'h6 d4 exd4 cxd4': '6.cxd4 builds the big centre. Meet ...Bb4+ with Bd2 or Nc3.',
      'h6 d4 exd4 cxd4 Bb4+': "6...Bb4+ checks. 7.Bd2 offers to trade off Black's most active piece.",
      'h6 d4 exd4 cxd4 Bb4+ Bd2': '7.Bd2 blocks the check and challenges the bishop. Black usually trades on d2.',
      'h6 d4 exd4 cxd4 Bb4+ Bd2 Bxd2+': '7...Bxd2+ trades. 8.Nbxd2 develops and guards e4; 8.Qxd2 is fine too.',
      'h6 d4 exd4 cxd4 Bb4+ Nc3': '7.Nc3 blocks with a piece that also guards e4. Castle next so the knight can move again.',
    },
  },
  {
    id: 'giuoco-pianissimo',
    name: 'Giuoco Pianissimo',
    lines: [`${IT} Bc5 d3`],
    plan: '4.d3 keeps e4 solid and avoids early fights. Castle, then c3, Re1 and Bb3; play d4 when everything is ready.',
    notes: {
      Nf6: '4...Nf6 develops and hits e4, which d3 already guards. Black can castle next.',
      'Nf6 Be3': "5.Be3 offers to trade Black's strong c5 bishop. If ...Bxe3 fxe3, the f-file opens for your rook.",
      'Nf6 Bg5': '5.Bg5 pins the f6 knight to the queen. Expect ...h6; keep the pin with Bh4 or take on f6.',
      'Nf6 Bg5 h6': '5...h6 asks the bishop. 6.Bh4 keeps the pin; 6.Bxf6 Qxf6 hands Black the bishop pair.',
      'Nf6 Bg5 h6 Bh4': "6.Bh4 keeps the pin. If ...g5 Bg3, Black's kingside is loosened for good.",
      'Nf6 Bg5 h6 Bh4 g5': "6...g5 frees the knight but weakens Black's king. Drop back with 7.Bg3; the bishop still eyes e5.",
      'Nf6 Bg5 h6 Bh4 g5 Bg3': "7.Bg3 keeps the bishop safe and aimed at e5. Later h4 can attack Black's pawns on g5 and h6.",
      'Nf6 Nc3': '5.Nc3 develops toward d5. With d3 played, ...Nxe4 tricks no longer work.',
      'Nf6 Nc3 O-O': '5...O-O. Bg5 now pins the knight to the queen, or Be3 challenges the c5 bishop.',
      'Nf6 Ng5': '5.Ng5 attacks f7 with knight and bishop. Black covers it with 5...O-O, and the knight often has to return.',
      'Nf6 Ng5 O-O': '5...O-O covers f7 with the rook. Your knight has no target left: develop with Nc3 and castle.',
      'Nf6 Ng5 O-O O-O': '6.O-O castles, but your g5 knight has no target. If 6...d5, bring it home with Nf3.',
      'Nf6 O-O': '5.O-O puts your king safe and readies Re1. c3 and h3 often come next.',
      'Nf6 O-O O-O': '5...O-O: both kings are safe. Play c3 and Re1, or h3 to keep the bishop off g4.',
      'Nf6 O-O O-O Bg5': '6.Bg5 pins the f6 knight to the queen. ...h6 asks it to take or drop back to h4.',
      'Nf6 O-O O-O c3': '6.c3 prepares d4 and gives the bishop a retreat on c2. Black usually answers ...d6.',
      'Nf6 O-O O-O c3 d6': '6...d6 holds e5. Re1, Nbd2 and Bb3 are your usual moves before d4.',
      'Nf6 O-O d6': '5...d6 supports e5 and opens the c8 bishop, which may pin your knight from g4. h3 rules that out.',
      'Nf6 O-O d6 h3': '6.h3 rules out ...Bg4. Next c3 and Re1, or Be3 against the c5 bishop.',
      'Nf6 O-O d6 h3 h6': '6...h6 copies your h3, keeping your pieces off g5. Continue with c3 and Re1, or Nc3.',
      'Nf6 O-O h6': '5...h6 stops Ng5 and Bg5. Continue with c3, Re1 and h3, or Nc3.',
      'Nf6 c3': '5.c3 prepares d4 and gives your bishop a retreat on c2 later.',
      'Nf6 h3': "5.h3 keeps Black's bishop off g4, so your knight cannot be pinned.",
      'Nf6 h3 h6': '5...h6 mirrors you. Nc3, c3 or O-O next; neither side allows a pin.',
      'Nf6 h3 h6 Nc3': '6.Nc3 develops. With d3 played, ...Nxe4 tricks fail; Be3 and O-O follow.',
      'Nf6 h3 h6 Nc3 O-O': '6...O-O. Castle too and play Be3: your king is safe and the centre stays closed.',
      d6: '4...d6 holds e5 and opens the c8 bishop. Same slow fight: castle, c3 and h3.',
      'd6 Nc3': '5.Nc3 brings out a knight. If ...Na5 attacks your bishop, step back to b3.',
      'd6 Nc3 Bg4 h3': '6.h3 asks the bishop to decide: ...Bxf3 Qxf3 gives you the bishop pair.',
      'd6 Ng5': '5.Ng5 hits f7 twice, threatening Bxf7+ or Nxf7. Black must cover it with ...Nh6 or the queen.',
      'd6 Ng5 Nh6': "5...Nh6 guards f7 from the rim. Bring the knight back and castle; Bxh6 later can double Black's pawns.",
      'd6 Ng5 Nh6 Nf3': "6.Nf3 brings the knight home. Castle next; Black's knight on h6 still needs a better square.",
      'd6 Ng5 Nh6 Nf3 Bg4': '6...Bg4 pins your knight to the queen. 7.c3 is useful: it keeps the c6 knight off d4, where it would hit f3 again.',
      h6: '4...h6 rules out Ng5 and Bg5. Use the time for c3 and a later d4.',
      'h6 c3': '5.c3 prepares d4 and gives your bishop a retreat on c2.',
    },
  },
  {
    id: 'giuoco-piano-castles',
    name: 'Giuoco Piano: 4.O-O',
    lines: [`${IT} Bc5 O-O`],
    plan: '4.O-O puts your king safe first. Next comes c3 and d4 for the centre, or d3 for the slow Pianissimo set-up.',
    notes: {
      Nf6: '4...Nf6 attacks e4. Defend it calmly with 5.d3.',
      'Nf6 Nc3 O-O': '5...O-O. Now d3 keeps e4 safe; then Bg5 or Be3.',
      'Nf6 Nc3 O-O d3': '6.d3 makes e4 safe for good. Bg5, Be3 or h3 come next.',
      'Nf6 Ng5 O-O': '5...O-O guards f7 with the rook, so your g5 knight has nothing to hit. Get Nc3 and d3 out.',
      'Nf6 Ng5 O-O Nc3': '6.Nc3 develops. If ...h6 kicks the g5 knight, it goes back to f3.',
      'Nf6 c3': '5.c3 prepares d4 but leaves e4 loose: 5...Nxe4 wins a pawn. 5.d3 first is safer.',
      'Nf6 c3 Nxe4': '5...Nxe4 grabs the pawn. Hit back with 6.d4, attacking the bishop and e5; Black stays slightly better.',
      'Nf6 c3 Nxe4 d4': "6.d4 hits the bishop and e5. Black's best is 6...d5, hitting your bishop back.",
      'Nf6 d3': '5.d3 guards e4 for good. c3, Re1 and Nbd2 follow, with d4 later.',
      'Nf6 d3 O-O Nc3': '6.Nc3 develops; with d3 in, e4 is safe. Bg5 pins, Be3 challenges the c5 bishop.',
      'Nf6 d3 O-O Nc3 d6': "6...d6 holds e5. Bg5 pins the knight, or h3 keeps Black's bishop off g4.",
      'Nf6 d3 a6': '5...a6 gives the bishop a retreat on a7. Carry on with c3, Re1 and Nbd2.',
      'Nf6 d4': '5.d4 opens lines while your king is already safe, usually at the cost of a pawn.',
      'Nf6 d4 Bxd4': '5...Bxd4 takes. Retake with 6.Nxd4; after ...Nxd4 you are a pawn down, but your pieces come out faster.',
      'Nf6 d4 Bxd4 Nxd4': "6.Nxd4 takes back. Black's best is 6...Nxd4; if 6...exd4, 7.e5 hits the f6 knight and you are better.",
      'Nf6 d4 exd4': '5...exd4 takes. 6.e5 is the sharp try; 6.c3 offers another pawn.',
      'Nf6 d4 exd4 e5': '6.e5 attacks the knight. 6...d5 hits back at your bishop; 7.exf6 dxc4 8.Re1+ is the Max Lange Attack.',
      'Nf6 d4 exd4 e5 Ng4': '6...Ng4 dodges the pawn. 7.Bf4 guards e5; h3 next chases the knight again.',
      d6: '4...d6 holds e5 and readies ...Bg4 to pin your knight. c3 and d4, or h3 first.',
      'd6 c3': '5.c3 prepares d4. If Black pins with ...Bg4, h3 asks the bishop to decide.',
      'd6 c3 Bg4': '5...Bg4 pins your knight. After h3, ...Bxf3 Qxf3 gives you the bishop pair.',
      'd6 d3': '5.d3 keeps everything protected. Watch for ...Bg4; h3 keeps the bishop out.',
      'd6 h3': '5.h3 keeps the bishop off g4. c3 and d4, or d3, can follow.',
      h6: '4...h6 stops Ng5 and Bg5. Use the time: c3 and d4 build the centre.',
      'h6 c3': '5.c3 prepares d4 with gain of time on the c5 bishop.',
      'h6 c3 Nf6': '5...Nf6 hits e4. 6.d4 is the point: after 6...exd4 7.cxd4 the bishop must move.',
      'h6 c3 Nf6 d4': '6.d4 hits the bishop and e5. Your king is castled, so the centre can open.',
      'h6 c3 Nf6 d4 exd4': '6...exd4 gives up the centre. 7.cxd4 builds pawns on e4 and d4.',
      'h6 c3 Nf6 d4 exd4 cxd4': "7.cxd4 completes your centre. Next e5 or d5 can kick Black's knights.",
      'h6 c3 Nf6 d4 exd4 cxd4 Bb4': '7...Bb4 is no check, as your king has castled. 8.e5 kicks the f6 knight and gains space.',
      'h6 c3 Nf6 d4 exd4 cxd4 Bb4 e5': '8.e5 kicks the f6 knight, and every square it can go to is poor. You are clearly better.',
      'h6 c3 Nf6 d4 exd4 cxd4 Bb6': '7...Bb6 keeps the bishop on the a7-g1 diagonal. Play e5 or Nc3: your centre is the trump.',
    },
  },
  {
    id: 'evans-gambit',
    name: 'Evans Gambit',
    lines: [`${IT} Bc5 b4`],
    plan: '4.b4 offers a pawn to deflect the bishop. After ...Bxb4, c3 and d4 gain time on it and build a big centre.',
    notes: {
      Bb6: '4...Bb6 declines the pawn. 5.a4 threatens a5 against the bishop and wins queenside space.',
      'Bb6 c3': '5.c3 prepares d4. Your b4 pawn already gains queenside space.',
      'Bb6 c3 d6': '5...d6 holds e5. a4 and a5 can harass the bishop on b6.',
      Bxb4: '4...Bxb4 accepts. 5.c3 hits the bishop and prepares d4.',
      'Bxb4 c3': '5.c3 kicks the bishop and readies d4. Black usually retreats to a5, still eyeing c3.',
      'Bxb4 c3 Ba5': '5...Ba5 is the main retreat. 6.d4: your centre and lead in development pay for the pawn.',
      'Bxb4 c3 Ba5 d4': '6.d4 opens lines while Black is uncastled. Castle next and bring the queen to b3 against f7.',
      'Bxb4 c3 Bc5': '5...Bc5 walks back into 6.d4, which hits the bishop and e5 at once and builds your centre.',
      'Bxb4 c3 Be7': '5...Be7 is a safe retreat. 6.d4 keeps building with gain of time.',
    },
  },
  {
    id: 'giuoco-piano-d4',
    name: 'Giuoco Piano: 4.d4',
    lines: [`${IT} Bc5 d4`],
    plan: '4.d4 opens the centre early, often as a gambit. After 4...exd4, c3 or O-O speeds up your development.',
    notes: {
      exd4: '4...exd4 takes. 5.c3 is the main move and hits d4; 5.O-O and 5.Ng5 play it as a gambit.',
      'exd4 Ng5': "5.Ng5 aims straight at f7. Black's best answer is 5...Nh6, guarding it.",
      'exd4 Ng5 Nh6': '5...Nh6 guards f7. You can still take there: Nxf7, Bxf7+ and Qh5+ wins back the pawn with the c5 bishop.',
      'exd4 Ng5 Nh6 Nxf7': '6.Nxf7 starts the trades: after 6...Nxf7 7.Bxf7+ Kxf7 8.Qh5+, your queen checks and takes the c5 bishop.',
      'exd4 Ng5 Nh6 Nxf7 Nxf7': '6...Nxf7. Now 7.Bxf7+ is a must: it drags the king to f7 so Qh5+ can hit the c5 bishop.',
      'exd4 Ng5 Nh6 Nxf7 Nxf7 Bxf7+': '7.Bxf7+ checks. After 7...Kxf7, 8.Qh5+ checks again and attacks the c5 bishop.',
      'exd4 Ng5 Nh6 Nxf7 Nxf7 Bxf7+ Kxf7': '7...Kxf7. 8.Qh5+ is the point: it checks the king and hits the c5 bishop at once.',
      'exd4 Ng5 Nh6 Nxf7 Nxf7 Bxf7+ Kxf7 Qh5+': "8.Qh5+ checks and hits the c5 bishop. Black can't save it: Qxc5 next makes material level.",
      'exd4 Ng5 Nh6 Nxf7 Nxf7 Bxf7+ Kxf7 Qh5+ g6': "8...g6 blocks the check. Take the bishop with 9.Qxc5: material is level, and Black's king can't castle.",
      'exd4 O-O': '5.O-O gets your king safe first. Next c3 opens lines, or e5 if Black plays ...Nf6.',
      'exd4 c3': '5.c3 gambits a pawn: if ...dxc3, Nxc3 develops with a lead and open lines.',
      'exd4 c3 Nf6': '5...Nf6 hits e4. 6.cxd4 Bb4+ reaches the main line of the Giuoco Piano; 6.e5 is the sharp try.',
      'exd4 c3 Nf6 cxd4 Bb4+ Nc3 Nxe4 O-O Bxc3': '8...Bxc3. Take back with 9.bxc3, or play 9.d5 first to hit the c6 knight. You are a pawn down but active.',
      'exd4 c3 Qf6 e5': '6.e5 hits the queen at once. Then cxd4 rebuilds your centre while the queen is pushed around.',
    },
  },
  {
    id: 'italian-four-knights',
    name: 'Italian Four Knights',
    lines: [`${IT} Bc5 Nc3`],
    plan: 'Your knight guards e4 and eyes d5. Play d3 early: until then, ...Nxe4 and ...d5 can win the piece back with a fork.',
    notes: {
      Nf6: '4...Nf6 completes the four knights. 5.d3 stops ...Nxe4 tricks for good.',
      'Nf6 O-O': '5.O-O allows the fork trick 5...Nxe4 6.Nxe4 d5. 5.d3 avoids it.',
      'Nf6 O-O d6': '5...d6 skips the fork trick. 6.d3 makes e4 safe for good.',
      'Nf6 O-O d6 d3': '6.d3 keeps e4 safe. Bg5, Be3 or Na4 come next.',
      'Nf6 d3': '5.d3 shores up e4. Next Bg5, Be3 or O-O; Nd5 can trade off the f6 knight.',
      'Nf6 d3 Ng4': '5...Ng4? leaves f7 bare: 6.Bxf7+ Kxf7 7.Ng5+ uncovers your queen on the g4 knight and wins a pawn.',
      'Nf6 d3 d6': '5...d6 mirrors you. Bg5 pins the f6 knight; Black may answer ...Na5 to trade your bishop.',
      'Nf6 d3 d6 Bg5': "6.Bg5 pins the knight. ...h6 and ...g5 break the pin but loosen Black's king.",
      'Nf6 d3 d6 Bg5 h6': '6...h6 asks the bishop. Bh4 keeps the pin; Bxf6 Qxf6 trades it for the knight.',
      'Nf6 d3 h6': "5...h6 stops Bg5. Be3 offers to trade Black's strong bishop.",
      'Nf6 d3 h6 Be3': '6.Be3 challenges the c5 bishop. If ...Bxe3 fxe3, the f-file opens for your rook.',
      'Nf6 d3 h6 Be3 Bxe3': "6...Bxe3. Retake 7.fxe3: the pawn covers d4 and f4, so Black's knights lose those squares.",
      'Nf6 d3 h6 Be3 Bxe3 fxe3': '7.fxe3 recaptures. Castle next: your rook then uses the f-file toward f7.',
      d6: '4...d6 holds e5 and readies ...Bg4 or ...Nf6. d3 and h3 keep things safe.',
      'd6 d3': "5.d3 supports e4. Black's ...Bg4 pin is the move to watch; h3 asks the question.",
      'd6 d3 Bg4': '5...Bg4 pins your knight. h3 forces a choice: ...Bxf3 gives you the bishop pair, ...Bh5 keeps the pin.',
      'd6 d3 Bg4 h3 Bh5': '6...Bh5 keeps your knight pinned to the queen. g4 can chase the bishop away, at the cost of loosening your kingside.',
      'd6 d3 Bg4 h3 Bh5 g4': '7.g4 breaks the pin: ...Bxg4 hxg4 just loses a piece for a pawn, so the bishop goes to g6.',
      'd6 d3 Bg4 h3 Bh5 g4 Bg6': "7...Bg6 drops back. Bring out Be3 and Qe2; your g4 and h3 pawns keep Black's pieces off f5 and g4.",
      'd6 d3 Bg4 h3 Bh5 g4 Bg6 Be3': '8.Be3 offers to swap the c5 bishop. If ...Bxe3, fxe3 guards d4 and f4.',
      'd6 d3 Nf6': '5...Nf6 completes development. Castle, or pin the knight with Bg5.',
      'd6 h3': "5.h3 keeps Black's bishop off g4, where it would pin your knight to the queen. Next d3 and castling.",
      h6: '4...h6 stops Bg5 and Ng5. d3, Be3 and castling keep things simple.',
      'h6 d3 d6 O-O Nf6': '6...Nf6 develops. h3 stops ...Bg4, and Be3 or Na4 take on the c5 bishop.',
      'h6 d3 d6 O-O Nf6 h3': "7.h3 keeps the c8 bishop off g4. Next Be3 or Na4 can swap off Black's c5 bishop.",
    },
  },
  {
    id: 'two-knights',
    name: 'Two Knights Defence',
    lines: [`${IT} Nf6`],
    plan: '3...Nf6 hits e4 and invites 4.Ng5 against f7. Choose: 4.d3 keeps it calm, 4.Ng5 attacks, 4.d4 opens the centre.',
    notes: {},
  },
  {
    id: 'two-knights-d3',
    name: 'Two Knights: 4.d3',
    lines: [`${IT} Nf6 d3`],
    plan: '4.d3 guards e4 and keeps the game slow: c3, O-O, Re1 and Bb3, then d4. It often becomes a Giuoco Pianissimo.',
    notes: {
      'Bb4+': '4...Bb4+ checks to provoke c3. Play 5.c3, which you wanted anyway; b4 can then chase the bishop.',
      Bc5: "4...Bc5 transposes to the Giuoco Pianissimo: both bishops aim at the other side's f-pawn.",
      'Bc5 Be3 Bb6': "5...Bb6 avoids the trade. Castle next: taking on b6 only opens the a-file for Black's rook.",
      'Bc5 Bg5 O-O': '5...O-O castles into your pin. Castle too or play Nc3; if ...h6, Bh4 keeps the knight pinned.',
      'Bc5 Bg5 O-O O-O': "6.O-O gets your king safe. Next c3 and Nbd2, while the pin keeps Black's f6 knight tied to the queen.",
      'Bc5 Bg5 d6': '5...d6 guards e5. Nc3 and Nd5 can add a second attacker on the pinned f6 knight.',
      'Bc5 Bg5 h6 Bxf6 Qxf6 Nc3 d6 Nd5': "8.Nd5 hits the queen and eyes c7. Black's best is 8...Qd8, guarding c7.",
      'Bc5 Bg5 h6 Bxf6 Qxf6 Nc3 d6 Nd5 Qd8': '8...Qd8 guards c7. 9.c3 keeps the c6 knight off d4 and b4; castle next.',
      'Bc5 Nc3 d6 O-O': '6.O-O puts your king in safety. If ...Na5 hits your bishop, drop it back to b3.',
      'Bc5 Nc3 h6 O-O d6': '6...d6 holds e5. 7.Na4 hits the c5 bishop, aiming to trade it off.',
      'Bc5 Ng5 O-O Nc3': '6.Nc3 brings a knight out. Your g5 knight has no target now; expect ...h6 to send it back.',
      'Bc5 Ng5 O-O Nc3 d6 h3': '7.h3 keeps the bishop off g4. The g5 knight still has nothing to do: bring it back via f3.',
      'Bc5 O-O O-O c3 d6 a4': '7.a4 grabs room on the queenside; b4 next can push the bishop back. Black often answers ...a5 or ...a6.',
      'Bc5 O-O d6 c3': '6.c3 prepares d4 and gives your bishop a retreat on c2. Next Re1, h3 and Nbd2.',
      'Bc5 O-O h6 Be3': "6.Be3 offers to swap Black's active c5 bishop. If ...Bxe3 fxe3, your rook gets the f-file.",
      'Bc5 c3 O-O O-O': '6.O-O. Both kings are safe; next Re1, Nbd2 and Bb3, or b4 to push the bishop back.',
      'Bc5 c3 O-O b4': "6.b4 kicks the bishop and grabs queenside room. Black's best is 6...Be7, then ...d5.",
      'Bc5 c3 h6 O-O': '6.O-O puts your king in safety. Next Re1, or b4 and a4 to push the c5 bishop back.',
      Be7: '4...Be7 is solid: Black castles and may push ...d5 later. Castle, then c3 and Re1.',
      d5: '4...d5 opens the centre. After 5.exd5 Nxd5 the knight is strong, but e5 needs guarding.',
      'd5 exd5': '5.exd5 trades a centre pawn. Black takes back with the knight; Re1 will then press on e5.',
      'd5 exd5 Nxd5': '5...Nxd5 centralises the knight. Castle and play Re1 to hit e5; Nc3 can challenge d5.',
      'd5 exd5 Nxd5 O-O': '6.O-O gets your king safe. Re1 next piles on e5.',
      'd5 exd5 Nxd5 O-O Be7': '6...Be7 prepares to castle. Re1 hits e5, and the d5 knight may need ...Be6 for support.',
      d6: '4...d6 guards e5 and frees the c8 bishop. Castle and prepare c3 and d4.',
      h6: '4...h6 stops Ng5 and Bg5. Continue with c3, O-O and Re1; d4 comes later.',
      'h6 Nc3': '5.Nc3 develops and guards e4. Be3 and h3 can follow.',
      'h6 Nc3 Bc5': '5...Bc5 aims at f2. With d3 played, a pawn guards e4; castle, or play h3 and Be3.',
      'h6 O-O': "5.O-O gets your king safe. c3 and Re1 next; Black's ...h6 rules out Ng5 ideas.",
      'h6 O-O Bc5': '5...Bc5 makes it a Giuoco Pianissimo. c3 and Re1, or h3, are the plans.',
      'h6 O-O Bc5 c3': '6.c3 prepares d4 and gives your bishop a retreat on c2.',
      'h6 O-O Bc5 c3 O-O': '6...O-O. Now 7.d4 hits the bishop and e5 at once, with your king already safe.',
      'h6 O-O Bc5 h3': '6.h3 mirrors ...h6: no pins on g4, and your king gets an escape square.',
      'h6 O-O Bc5 h3 d6': '6...d6 holds e5. c3, Re1 and Nbd2 finish your set-up.',
      'h6 h3': "5.h3 keeps Black's bishop off g4 and gives your king an escape square later. c3 and O-O next.",
    },
  },
  {
    id: 'two-knights-ng5',
    name: 'Two Knights: 4.Ng5',
    lines: [`${IT} Nf6 Ng5`],
    plan: '4.Ng5 hits f7 twice. After 4...d5 5.exd5 Na5 you can keep an extra pawn, but Black gets fast development.',
    notes: {
      Bc5: '4...Bc5 is the Traxler: Black ignores f7 and hits f2. 5.Bxf7+ is the safe capture; 5.Nxf7 gets wild.',
      'Bc5 Bxf7+': "5.Bxf7+ grabs the pawn with check. Black's king must move and can no longer castle.",
      'Bc5 Nxf7': '5.Nxf7 forks queen and rook, but 5...Bxf2+ drags your king into the open.',
      'Bc5 Nxf7 Bxf2+': '5...Bxf2+ is the point. 6.Kxf2 Nxe4+ exposes your king; 6.Kf1 avoids the knight check.',
      'Bc5 Nxf7 Bxf2+ Kf1': '6.Kf1 avoids ...Nxe4 with check. Black follows with 6...Qe7, aiming down the e-file.',
      'Bc5 Nxf7 Bxf2+ Kf1 Qe7': '6...Qe7 eyes e4. Take the rook with 7.Nxh8: Black gets an attack, but you stay better.',
      'Bc5 Nxf7 Bxf2+ Kf1 Qe7 Nxh8': '7.Nxh8 wins a rook. After 7...d5 8.exd5 Nd4, 9.d6! gives back a pawn to slow the attack.',
      'Bc5 Nxf7 Bxf2+ Kf1 Qe7 Nxh8 d5': '7...d5 hits your bishop and opens lines. Take with 8.exd5: you are a rook up, but must defend carefully.',
      'Bc5 Nxf7 Bxf2+ Kf1 Qe7 Nxh8 d5 exd5': '8.exd5. Expect 8...Nd4; then 9.d6!, giving back a pawn, is the move that keeps you on top.',
      Nxe4: "4...Nxe4 grabs a pawn but drops f7. 5.Bxf7+ Ke7 leaves Black's king stuck in the centre.",
      'Nxe4 Bxf7+': '5.Bxf7+ forces 5...Ke7, as the g5 knight guards f7. Black can never castle now.',
      'Nxe4 Bxf7+ Ke7': '5...Ke7 is forced. 6.d4 is strongest and opens lines; 6.d3 kicks the e4 knight more calmly.',
      'Nxe4 Bxf7+ Ke7 d3': '6.d3 hits the e4 knight. It must retreat, and your bishop can drop back to b3.',
      'Nxe4 Bxf7+ Ke7 d3 Nf6': "6...Nf6 retreats. 7.Bb3 saves your bishop, and Black's king is stuck on e7.",
      'Nxe4 Bxf7+ Ke7 d3 Nf6 Bb3': "7.Bb3. Material is level, but Black's king can never castle. Castle and bring Nc3 out.",
      'Nxe4 Bxf7+ Ke7 d3 Nf6 Bb3 d5': '7...d5 builds a centre to shield the king. 8.c4 hits it at once; castling is also good.',
      'Nxe4 Bxf7+ Ke7 d3 Nf6 Bb3 d5 O-O': "8.O-O gets your king safe while Black's stays on e7. Next c4 or Re1 opens lines toward it.",
      'Nxe4 Bxf7+ Ke7 d4': "6.d4 opens the centre while Black's king is stuck on e7. Your pieces will reach it first.",
      Qe7: '4...Qe7? fails to guard f7: 5.Bxf7+ wins a pawn, since ...Qxf7 Nxf7 drops the queen.',
      'Qe7 Bxf7+': "5.Bxf7+ wins a pawn. Black can't take: 5...Qxf7 6.Nxf7 loses the queen, so the king must move.",
      'Qe7 Bxf7+ Kd8': "5...Kd8. Drop the bishop back to b3: you are a pawn up and Black can't castle.",
      'Qe7 Bxf7+ Kd8 Bc4': '6.Bc4 keeps the bishop on its best line. You are a pawn up; if ...Na5, Nf7+ wins the h8 rook.',
      d5: "4...d5 blocks your bishop's line to f7 and strikes at e4. Take with 5.exd5.",
      'd5 exd5': '5.exd5 reopens the line to f7. 5...Na5 is best; 5...Nxd5 allows a dangerous attack.',
      'd5 exd5 Na5': '5...Na5 hits your bishop and gives up a pawn for time. 6.Bb5+ keeps the bishop active.',
      'd5 exd5 Na5 Bb5+': '6.Bb5+ checks. After 6...c6 7.dxc6 bxc6 you are a pawn up; Black gets open lines.',
      'd5 exd5 Na5 Bb5+ Bd7': '6...Bd7 blocks with a piece. 7.Qe2 defends the bishop and presses e5.',
      'd5 exd5 Na5 Bb5+ Bd7 Qe2': '7.Qe2 holds b5 and eyes e5. Black trades with ...Bxb5 or develops with ...Bd6.',
      'd5 exd5 Na5 Bb5+ Bd7 Qe2 Bd6': '7...Bd6 develops and guards e5. You keep the extra pawn: castle and play Nc3.',
      'd5 exd5 Na5 Bb5+ Bd7 Qe2 Bd6 Nc3': "8.Nc3 is a little slow: after 8...c6 Black's pieces become active and the game is level. Castling first was better.",
      'd5 exd5 Na5 Bb5+ c6': '6...c6 blocks and hits the bishop. Take with 7.dxc6, then drop the bishop back to e2 or d3.',
      'd5 exd5 Na5 Bb5+ c6 dxc6': "7.dxc6 bxc6 leaves you a pawn up. Black's lead in development is the compensation.",
      'd5 exd5 Na5 Bb5+ c6 dxc6 bxc6': '7...bxc6 attacks your bishop. Retreat to e2, the main line, or d3, and bring the g5 knight back soon.',
      'd5 exd5 Na5 Bb5+ c6 dxc6 bxc6 Bd3': '8.Bd3 keeps the bishop near your king. Black has ...h6 or ...Nd5; castle soon.',
      'd5 exd5 Na5 Bb5+ c6 dxc6 bxc6 Bd3 Nd5': "8...Nd5 uncovers Black's queen onto g5: your knight is attacked. Bring it back to f3 or e4.",
      'd5 exd5 Na5 Bb5+ c6 dxc6 bxc6 Bd3 Ng4': '8...Ng4 eyes f2 and h2. 9.Ne4 is best: the knight comes back and guards f2.',
      'd5 exd5 Na5 Bb5+ c6 dxc6 bxc6 Bd3 h6': '8...h6 kicks the knight. Play 9.Ne4: after 9.Nf3? e4, the pawn forks bishop and knight.',
      'd5 exd5 Na5 Bb5+ c6 dxc6 bxc6 Be2': '8.Be2 is the main line. Black plays 8...h6, chasing your knight back to f3.',
      'd5 exd5 Na5 Bb5+ c6 dxc6 bxc6 Qf3': '8.Qf3 attacks c6 and pins it to the a8 rook. Black replies 8...Rb8, 8...Be7 or 8...h6.',
      'd5 exd5 Nd4': "5...Nd4 is the Fritz Variation. 6.c3 kicks the knight; Black's answer 6...b5 hits your bishop.",
      'd5 exd5 Nd4 c3': '6.c3 attacks the d4 knight. The main reply 6...b5 7.Bf1 Nxd5 leads to sharp play.',
      'd5 exd5 Nd4 c3 Nf5': '6...Nf5 retreats. You keep the extra pawn; 7.d3 and castling get your pieces out.',
      'd5 exd5 Nd4 d6': '6.d6 returns the extra pawn to open lines toward f7. 6.c3, kicking the knight, was stronger.',
      'd5 exd5 Nd4 d6 Qxd6': "6...Qxd6 takes back, and material is level. 7.d3 is best; 7.Bxf7+ grabs a pawn, but Black's pieces get active.",
      'd5 exd5 Nd4 d6 Qxd6 Bxf7+': "7.Bxf7+ wins a pawn. After 7...Ke7, drop the bishop back to b3: Black's king is exposed, but Black's pieces are active.",
      'd5 exd5 Nxd5': '5...Nxd5 is a mistake. 6.d4 opens lines; 6.Nxf7, the Fried Liver, drags the king out.',
      'd5 exd5 Nxd5 Nxf7': '6.Nxf7 is the Fried Liver: a knight for a pawn to pull the king to f7.',
      'd5 exd5 Nxd5 Nxf7 Kxf7': '6...Kxf7 takes. 7.Qf3+ hits the king and the d5 knight, pinned by your bishop on c4.',
      'd5 exd5 Nxd5 Nxf7 Kxf7 Qf3+': '7.Qf3+ forces the king forward: 7...Ke6 holds d5. Other king moves let you take on d5.',
      'd5 exd5 Nxd5 Nxf7 Kxf7 Qf3+ Ke6': '7...Ke6 guards the knight with the king. 8.Nc3 attacks d5 a third time.',
      'd5 exd5 Nxd5 Nxf7 Kxf7 Qf3+ Ke6 Nc3': "8.Nc3 piles on d5. Black's king is stuck in the centre; d4 next opens more lines.",
      'd5 exd5 Nxd5 Nxf7 Kxf7 Qf3+ Ke6 Nc3 Nd4': '8...Nd4 hits your queen but leaves the d5 knight short of guards: 9.Bxd5+ takes it with check.',
      'd5 exd5 Nxd5 Nxf7 Kxf7 Qf3+ Ke8': "7...Ke8 gives up d5: 8.Bxd5 leaves you a pawn up, and Black's king has lost castling.",
      'd5 exd5 Nxd5 Nxf7 Kxf7 Qf3+ Ke8 Bxd5': "8.Bxd5 wins the piece back. You are a pawn up and Black's king has lost the right to castle.",
      'd5 exd5 Nxd5 Nxf7 Kxf7 Qf3+ Ke8 Bxd5 Qf6': "8...Qf6 offers to trade queens. First 9.Bxc6+ bxc6 breaks up Black's pawns; you stay a pawn up.",
      'd5 exd5 Nxd5 Nxf7 Qh4': '6...Qh4 saves the queen but leaves the d5 knight: 7.Bxd5 takes it, and your f7 knight still hits the h8 rook.',
      'd5 exd5 Nxd5 Nxf7 Qh4 Bxd5': '7.Bxd5 grabs the knight, and your f7 knight still hits the h8 rook. You are winning material.',
      'd5 exd5 Nxd5 Nxf7 Qh4 Bxd5 Nb4': '7...Nb4 hits your bishop and c2. Take the rook first: 8.Nxh8 keeps you well ahead.',
      'd5 exd5 Nxd5 Nxf7 Qh4 Bxd5 Nb4 Nxh8': '8.Nxh8 wins the rook. After 8...Nxd5 you are a rook up; Qf3 next hits the d5 knight.',
      'd5 exd5 Nxd5 Nxf7 Qh4 Bxd5 Nb4 Nxh8 Nxd5': '8...Nxd5 takes your bishop. You are a rook up; 9.Qf3 hits the d5 knight and guards f2.',
      'd5 exd5 Nxd5 d4': '6.d4 opens the centre and keeps the pressure on f7 and d5. Your pieces arrive first.',
      'd5 exd5 b5': '5...b5 offers a pawn to deflect your bishop. 6.Bf1 hits b5 and keeps the pawn on d5.',
      'd5 exd5 b5 Bxb5': '6.Bxb5 grabs the pawn, but 6...Qxd5 hits g2 and b5 at once. 6.Bf1 kept more.',
      'd5 exd5 b5 Bxb5 Qxd5': '6...Qxd5 hits g2 and your bishop. 7.Bxc6+ trades the bishop off with check; then deal with g2.',
      'd5 exd5 b5 Bxb5 Qxd5 Bxc6+': '7.Bxc6+ trades your bishop off with check. After 7...Qxc6 the queen still hits g2: castle or play Qf3.',
      'd5 exd5 b5 Bxb5 Qxd5 Bxc6+ Qxc6': '7...Qxc6 still eyes g2. 8.O-O or 8.Qf3 deals with it; you are a pawn up.',
      'd5 exd5 b5 Bxb5 Qxd5 Bxc6+ Qxc6 O-O': "8.O-O tucks your king away. You are a pawn up, but Black's bishops are active.",
      'd5 exd5 b5 Bxb5 Qxd5 Bxc6+ Qxc6 O-O Bb7': '8...Bb7 lines up queen and bishop on g2. 9.Qf3 is the only good move: it blocks the line and offers a queen trade.',
    },
  },
  {
    id: 'two-knights-d4',
    name: 'Two Knights: 4.d4',
    lines: [`${IT} Nf6 d4`],
    plan: '4.d4 opens the centre at once. After 4...exd4, castle or push e5 and use your lead in development.',
    notes: {
      Nxe4: '4...Nxe4 grabs a pawn but leaves the knight loose. Hit back at once with 5.dxe5 or 5.d5.',
      'Nxe4 dxe5': '5.dxe5 gains space and threatens 6.Qd5, hitting the e4 knight and mate on f7.',
      'Nxe4 dxe5 Nc5': "5...Nc5 hits your bishop. Develop with 6.Nc3 or 6.Qe2: Black's king is still in the middle, and you are clearly better.",
      'Nxe4 dxe5 Nc5 Qd5': '6.Qd5 attacks the c5 knight and f7. Black guards both with 6...Ne6.',
      d6: '4...d6 holds e5 but is passive. 5.d5 gains space; 5.O-O keeps the tension.',
      exd4: '4...exd4 takes. 5.O-O is the main move; 5.e5 kicks the knight, and 5...d5 hits back.',
      'exd4 O-O': "5.O-O ignores the pawn: if 5...Nxe4, 6.Re1 pins the knight to Black's king.",
      'exd4 O-O Bc5 e5 d5': '6...d5 hits your bishop. Ignore it: 7.exf6 takes the knight, and if ...dxc4, Re1+ opens the e-file.',
      'exd4 O-O Bc5 e5 d5 exf6': '7.exf6 takes the knight. Black must take your bishop with 7...dxc4; then 8.Re1+ checks down the open e-file.',
      'exd4 O-O Bc5 e5 d5 exf6 dxc4': '7...dxc4. 8.Re1+ checks down the e-file; next fxg7 attacks the h8 rook.',
      'exd4 O-O Be7': '5...Be7 prepares to castle. Take the pawn back with 6.Nxd4 and enjoy your space.',
      'exd4 O-O Nxe4': '5...Nxe4 grabs a pawn. 6.Re1 pins it; after 6...d5 7.Bxd5 Qxd5 8.Nc3 you win the piece back.',
      'exd4 O-O Nxe4 Re1': '6.Re1 pins the knight. 6...d5 defends it, but 7.Bxd5 Qxd5 8.Nc3 hits queen and knight.',
      'exd4 O-O Nxe4 Re1 d5': '6...d5 props up the knight. 7.Bxd5 Qxd5 8.Nc3 wins the material back.',
      'exd4 O-O Nxe4 Re1 d5 Bxd5': '7.Bxd5 deflects the queen. After 7...Qxd5 8.Nc3 attacks the queen and the pinned knight.',
      'exd4 O-O Nxe4 Re1 d5 Bxd5 Qxd5': '7...Qxd5 takes. 8.Nc3 hits the queen, and Nxe4 next regains the piece.',
      'exd4 O-O Nxe4 Re1 d5 Bxd5 Qxd5 Nc3': '8.Nc3 attacks queen and knight. The queen moves, and you take on e4.',
      'exd4 O-O d6': '5...d6 is passive. 6.Nxd4 wins the pawn back, and your pieces are freer.',
      'exd4 e5': '5.e5 kicks the knight. 5...d5 is the right answer: it hits your bishop.',
      'exd4 e5 Ng4 O-O Bc5 Bf4': '7.Bf4 guards e5. Next h3 kicks the g4 knight to the edge.',
      'exd4 e5 Ng4 O-O Bc5 Bf4 O-O': "7...O-O. Now 8.h3 kicks the knight: on h6 it can be taken, breaking up Black's king pawns.",
      'exd4 e5 Ng4 O-O Bc5 Bf4 O-O h3': "8.h3 kicks the knight. After 8...Nh6 9.Bxh6 gxh6, Black's king has lost its pawn cover.",
      'exd4 e5 d5': "5...d5 hits your bishop. 6.Bb5 is the right square: it pins the c6 knight to Black's king.",
      'exd4 e5 d5 Bb5': "6.Bb5 pins the c6 knight to the king. Black's knight goes to e4; then Nxd4 wins back your pawn.",
    },
  },
  {
    id: 'two-knights-nc3',
    name: 'Two Knights: 4.Nc3',
    lines: [`${IT} Nf6 Nc3`],
    plan: '4.Nc3 guards e4, but allows the fork trick 4...Nxe4 5.Nxe4 d5. After 4...Bc5, play d3 and develop calmly.',
    notes: {
      Bb4: '4...Bb4 hits the knight that guards e4, threatening ...Bxc3 and ...Nxe4. d3 or Nd5 answers it.',
      'Bb4 d3': '5.d3 guards e4 with a pawn, so ...Bxc3 no longer wins it. Castle next.',
      Bc5: '4...Bc5 makes it the Italian Four Knights. 5.d3 stops ...Nxe4 tricks for good.',
      'Bc5 Ng5': '5.Ng5 hits f7, but 5...O-O covers it, and the knight achieves nothing. 5.d3 was steadier.',
      'Bc5 Ng5 O-O': '5...O-O guards f7 with the rook. Guard e4 with 6.d3 and bring the g5 knight home soon.',
      'Bc5 Ng5 O-O d3': '6.d3 guards e4. Bring the g5 knight back to f3 soon: it has no target, and ...h6 would kick it.',
      'Bc5 O-O d6 d3 Bg4': '6...Bg4 pins your knight to the queen. 7.h3 asks the bishop: take on f3, or step back to h5.',
      'Bc5 O-O d6 d3 Bg4 h3': '7.h3 asks the bishop. If ...Bxf3, Qxf3 brings your queen out; if ...Bh5, Nd5 is a good square for your knight.',
      'Bc5 d3 d6 Bg5 h6 Bh4': '7.Bh4 keeps the pin, but Black breaks it with 7...g5. Taking on f6 and playing Nd5 was a bit better.',
      'Bc5 d3 h6 Nd5': "6.Nd5 puts your knight on a strong central square and offers to trade off Black's f6 knight.",
      'Bc5 d3 h6 O-O O-O Be3': '7.Be3 offers to swap the c5 bishop. If ...Bxe3 fxe3, your rook gets the f-file and the e3 pawn guards d4.',
      Nxe4: '4...Nxe4 is the fork trick: after 5.Nxe4 d5, Black forks bishop and knight and wins the piece back.',
      'Nxe4 Nxe4': '5.Nxe4 takes the knight. 5...d5 now forks your bishop on c4 and knight on e4.',
      'Nxe4 Nxe4 d5': '5...d5 forks. Save the bishop with 6.Bd3; Black regains the piece and gets a free centre.',
      'Nxe4 Nxe4 d5 Bd3': '6.Bd3 saves the bishop near your king. After 6...dxe4 7.Bxe4 material is level.',
      'Nxe4 Nxe4 d5 Bd3 dxe4': '6...dxe4 regains the piece and hits your bishop. 7.Bxe4 wins the pawn back.',
      'Nxe4 Nxe4 d5 Bd3 dxe4 Bxe4': '7.Bxe4 restores material. Castle and play d3 or c3 with d4; Black is free and easy.',
      'Nxe4 Nxe4 d5 Bd3 dxe4 Bxe4 Bd6': '7...Bd6 develops and guards e5. Castle, then d4 or d3; the position is level.',
      'Nxe4 Nxe4 d5 Bd3 dxe4 Bxe4 Bd6 O-O': '8.O-O gets your king safe. Next Re1 and d3 or d4 to finish your set-up.',
      'Nxe4 Nxe4 d5 Bd3 dxe4 Bxe4 Bd6 O-O O-O': '8...O-O. Both kings are safe and material is level. Re1 and d3, or c3 and d4, finish your set-up.',
      d5: '4...d5 opens the centre early. Take with 5.exd5: your bishop and knight then hit d5 together.',
      'd5 exd5': '5.exd5 wins a pawn for now. If 5...Nxd5, your c3 knight and bishop both hit the knight.',
      'd5 exd5 Nd4': '5...Nd4 centralises the knight instead of taking back. You keep the extra pawn; develop and castle.',
      d6: '4...d6 leaves f7 weak: 5.Ng5 hits it twice, and Black must give a pawn with ...d5.',
      'd6 Ng5': "5.Ng5 hits f7 twice. Black's best is 5...d5, but after exd5 you win a pawn.",
      'd6 Ng5 d5': "5...d5 blocks the bishop's line to f7. Take with 6.exd5: you are a pawn up.",
      'd6 Ng5 d5 exd5': "6.exd5 wins a pawn. Black's best is 6...Na5, hitting your bishop; Bb5+ keeps it active.",
      h6: '4...h6 stops Ng5 and Bg5 but costs time. d3 next shuts out the fork trick.',
      'h6 O-O': '5.O-O allows the fork trick 5...Nxe4 6.Nxe4 d5; d3 first avoids it.',
    },
  },
  {
    id: 'two-knights-castles',
    name: 'Two Knights: 4.O-O',
    lines: [`${IT} Nf6 O-O`],
    plan: '4.O-O gets your king safe first. 4...Bc5 leads to a normal Italian; after 4...Nxe4, 5.Bd5 wins the pawn back.',
    notes: {
      Bc5: '4...Bc5 gives a Giuoco Piano with you already castled. d3, or c3 and d4, are the plans.',
      'Bc5 Nc3': '5.Nc3 allows the fork trick 5...Nxe4 6.Nxe4 d5. d3 first is safer.',
      'Bc5 Ng5': '5.Ng5 attacks f7, but Black is well developed: 5...O-O or 5...d5 meets it.',
      Nxe4: '4...Nxe4 grabs the pawn. 5.Bd5 wins it back; 5.Re1? d5 keeps Black a pawn up.',
      'Nxe4 d3': '5.d3 kicks the knight. After it retreats, Re1 and Nxe5 win your pawn back.',
      d5: '4...d5 opens lines too soon. 5.exd5 Nxd5 6.d4 puts the e5 pawn and d5 knight under fire.',
      'd5 exd5': "5.exd5 takes. After 5...Nxd5, 6.d4 or 6.Re1 hits e5 while Black's king is still in the middle.",
    },
  },
  {
    id: 'hungarian',
    name: 'Hungarian Defence',
    lines: [`${IT} Be7`],
    plan: '3...Be7 is solid but passive: Black avoids a fight over f7. Take space with d4, castle, and use your freer pieces.',
    notes: {
      'O-O': '4.O-O keeps the choice of d4 or d3. Black continues ...Nf6 and ...O-O.',
      'O-O Nf6': '4...Nf6 hits e4. 5.d4 is the active answer: after 5...exd4 6.Nxd4 your knight rules the centre.',
      c3: '4.c3 prepares d4 but is a bit slow: Black gets ...Nf6 and ...d5 in. 4.d4 at once was stronger.',
      'c3 Nf6': '4...Nf6 attacks e4. Guard it with 5.d3; Black may answer ...d5 to fight for the centre.',
      d3: '4.d3 keeps it slow. Castle, then c3 and d4.',
      d4: '4.d4 claims the centre at once. Black must give it up with ...exd4 or hold with ...d6.',
      'd4 d6': '4...d6 holds e5. 5.d5 gains space and pushes the c6 knight back.',
      'd4 exd4': '4...exd4 hands you the centre. 5.Nxd4 takes back; 5.c3 is a gambit.',
      'd4 exd4 Nxd4': '5.Nxd4 recaptures with a centralised knight. Castle next; Black is solid but cramped.',
      'd4 exd4 Nxd4 Ne5': '5...Ne5 attacks your bishop. Drop it back to b3, where it still aims at f7; f4 later kicks the knight.',
      'd4 exd4 Nxd4 Ne5 Bb3': '6.Bb3 keeps the bishop on its line to f7. Next Nc3, and f4 to chase the e5 knight.',
      'd4 exd4 Nxd4 Ne5 Bb3 Nf6': '6...Nf6 hits e4. 7.Nc3 guards it and brings another piece out.',
      'd4 exd4 Nxd4 Ne5 Bb3 Nf6 Nc3': '7.Nc3 guards e4. Castle next, then f4 can kick the e5 knight.',
      'd4 exd4 Nxd4 d6': '5...d6 frees the c8 bishop. Bring out 6.Nc3 and castle: your knight on d4 gives you more room.',
      'd4 exd4 c3': "5.c3 offers a pawn to open lines. Black's best answer is 5...Na5, chasing your bishop off its line to f7.",
      'd4 exd4 c3 dxc3': '5...dxc3 grabs a second pawn, but it costs time. 6.Nxc3 brings a knight out, and your pieces are far ahead.',
      'd4 exd4 c3 dxc3 Qd5': '6.Qd5 threatens Qxf7 mate. Only 6...Nh6 holds; 6.Nxc3 was stronger.',
      'd4 exd4 c3 dxc3 Qd5 Nh6': '6...Nh6 guards f7. 7.Bxh6 takes that guard away: if ...gxh6, Qxf7 is mate.',
      'd4 exd4 c3 dxc3 Qd5 Nh6 Bxh6': "7.Bxh6 removes f7's guard. Black must castle at once: ...gxh6 runs into Qxf7 mate.",
      'd4 exd4 c3 dxc3 Qd5 Nh6 Bxh6 O-O': "7...O-O guards f7 with the rook. 8.Bxg7 Kxg7 9.Nxc3 levels material and leaves Black's king bare.",
    },
  },
  {
    id: 'anti-fried-liver',
    name: 'Anti-Fried Liver Defence',
    lines: [`${IT} h6`],
    plan: '3...h6 stops Ng5 for good but spends a move. Use it: c3 and d4 for the centre, or castle first and then d4.',
    notes: {
      Nc3: '4.Nc3 develops and guards e4. d3 and Be3 can follow.',
      'Nc3 Bc5': '4...Bc5 aims at f2. Play d3 to shore up e4; Be3 can then challenge the bishop.',
      'Nc3 Bc5 d3': '5.d3 shores up e4 and frees the c1 bishop. Be3 or castling comes next.',
      'Nc3 Bc5 d3 Nf6': '5...Nf6 attacks e4, but your d3 pawn guards it. Castle next; Be3 offers to swap off the c5 bishop.',
      'Nc3 Bc5 d3 Nf6 O-O': "6.O-O puts your king in safety. Next Be3 or Na4 can swap off the c5 bishop, Black's most active piece.",
      'Nc3 Bc5 d3 d6': '5...d6 holds e5. With ...h6 covering g5, your bishop goes to e3; castle and play h3.',
      'Nc3 Nf6': '4...Nf6 hits e4. Play d3 soon: until then ...Nxe4 and ...d5 is the fork trick.',
      'Nc3 Nf6 d3': '5.d3 guards e4 with a pawn, so ...Nxe4 and ...d5 no longer wins your piece back. Castle and bring out the c1 bishop.',
      'Nc3 Nf6 d4': '5.d4 opens the centre while Black has spent a move on ...h6. Answer ...exd4 with Nxd4.',
      'Nc3 Nf6 d4 Bb4': '5...Bb4 pins your c3 knight to your king, so it no longer guards e4. 6.dxe5 hits the f6 knight first.',
      'Nc3 Nf6 d4 Bb4 dxe5': '6.dxe5 attacks the f6 knight. Its best square is g4, hitting your e5 pawn; Bf4 then guards it.',
      'Nc3 Nf6 d4 Bb4 dxe5 Bxc3+ bxc3 Nxe4 Qd5 O-O': '8...O-O covers f7 but drops the knight: 9.Qxe4 leaves you a whole piece up.',
      'O-O': '4.O-O gets your king safe. c3 and d4 can follow, since ...h6 cost Black time.',
      'O-O Bc5': '4...Bc5 gives a Giuoco Piano where ...h6 is already played. c3 and d4 are strong now.',
      'O-O Bc5 c3 Nf6 d4 exd4 cxd4 Bb6 e5': '8.e5 kicks the f6 knight, which has no good square: ...Nh7 and ...Ng4 put it on the edge.',
      'O-O Bc5 c3 Nf6 d4 exd4 cxd4 Bb6 e5 Nh7': '8...Nh7 parks the knight on the edge. 9.d5 now kicks the c6 knight too, and your pawns take over the centre.',
      'O-O Bc5 d4 exd4 c3': '6.c3 offers a pawn: if 6...dxc3, Bxf7+ and Qd5+ picks up the c5 bishop.',
      'O-O Nf6': '4...Nf6 attacks e4. Re1 or Nc3 defends it; d3 is the quiet way.',
      'O-O Nf6 Nc3': '5.Nc3 develops but allows the fork trick 5...Nxe4 6.Nxe4 d5. d3 first is safer.',
      'O-O Nf6 Nc3 Bc5': '5...Bc5 develops. 6.d3 shuts out the fork trick ...Nxe4 and ...d5.',
      'O-O Nf6 Nc3 Bc5 d3': '6.d3 keeps e4 solid. Next Be3 to challenge the bishop, or h3.',
      'O-O Nf6 Nc3 Bc5 d3 O-O': '6...O-O: both kings are safe. Be3 challenges the c5 bishop; h3 keeps ...Bg4 out.',
      'O-O Nf6 Nc3 Bc5 d3 O-O h3': '7.h3 keeps the bishop off g4 and gives your king air. Be3 comes next.',
      'O-O Nf6 Nc3 Bc5 d3 d6 h3 O-O': "7...O-O. Both kings are safe; Na4 or Be3 can now swap off the c5 bishop, Black's most active piece.",
      'O-O Nf6 Re1': '5.Re1 guards e4 and prepares c3 and d4.',
      'O-O Nf6 Re1 Bc5': '5...Bc5 eyes f2, which only your king guards now. c3 and d4 gain time on the bishop.',
      'O-O Nf6 Re1 Bc5 c3': '6.c3 prepares d4, which will hit the c5 bishop and grab the centre.',
      'O-O Nf6 Re1 Bc5 c3 O-O': '6...O-O. Now 7.d4 is strong: it hits e5 and, after ...exd4 cxd4, the bishop too.',
      'O-O Nf6 Re1 Bc5 c3 O-O d4': '7.d4 opens the centre while your king is safe. After 7...exd4 8.cxd4 the bishop is attacked.',
      'O-O Nf6 Re1 Bc5 c3 O-O d4 exd4': '7...exd4 gives up the centre. 8.cxd4 hits the bishop and leaves you two pawns side by side in the middle.',
      'O-O Nf6 Re1 Bc5 c3 O-O d4 exd4 cxd4': "8.cxd4 hits the bishop and gives you two strong centre pawns. Next e5 or d5 can kick Black's knights.",
      'O-O Nf6 Re1 Bc5 c3 O-O d4 exd4 cxd4 Bb4': '8...Bb4 attacks your rook on e1. Block with 9.Nc3, which also brings a knight out.',
      'O-O Nf6 d3': '5.d3 guards e4 with a pawn. Next c3 and Re1; push d4 once your pieces are out.',
      'O-O Nf6 d3 Bc5 h3 O-O': '6...O-O. Both kings are safe. Play c3 and Re1, then aim for d4 when it is ready.',
      'O-O Nf6 d4': '5.d4 opens lines with your king already castled. After 5...exd4, 6.e5 or 6.Re1 hit back at once.',
      'O-O d6': '4...d6 holds e5. c3 and d4 build your centre; h3 stops ...Bg4.',
      c3: "4.c3 prepares d4. Black's ...h6 did nothing to stop it.",
      'c3 Bc5': '4...Bc5 walks into your plan: 5.d4 hits the bishop and e5 together.',
      'c3 Bc5 O-O': '5.O-O castles first. Next d4 hits the bishop and e5.',
      'c3 Bc5 O-O d6': '5...d6 holds e5. 6.d4 still hits it and, after ...exd4 cxd4, the bishop too.',
      'c3 Bc5 O-O d6 d4': '6.d4 attacks the c5 bishop and e5 at once. Black usually takes; cxd4 then gives you two centre pawns.',
      'c3 Bc5 O-O d6 d4 exd4': '6...exd4 gives up the centre. Retake with 7.cxd4: the bishop is attacked again and must step back.',
      'c3 Bc5 O-O d6 d4 exd4 cxd4': '7.cxd4 hits the bishop again. It must retreat: 7...Nxd4? 8.Nxd4 Bxd4 9.Qxd4 just loses a piece.',
      'c3 Bc5 O-O d6 d4 exd4 cxd4 Bb6': '7...Bb6 keeps the bishop aimed at d4. Play Nc3 and h3, then d5 can push the c6 knight away.',
      'c3 Nf6': '4...Nf6 attacks e4. 5.d3 keeps it solid; 5.d4 is more ambitious.',
      'c3 Nf6 d3': '5.d3 guards e4 for good. Castle, then Re1 or Bb3; d4 can still come later.',
      'c3 Nf6 d3 Bc5': '5...Bc5 aims at f2. Castle, and b4 can push the bishop back, with a4 to follow.',
      'c3 Nf6 d3 Bc5 O-O d6': '6...d6 holds e5. Re1, Nbd2 and Bb3 finish your set-up; b4 can push the bishop back.',
      'c3 Nf6 d3 Be7': '5...Be7 guards the f6 knight and prepares castling. Castle too, then Re1 and Nbd2.',
      'c3 Nf6 d3 d6': '5...d6 keeps e5 firm. Castle, then Nbd2, Re1 and Bb3 before d4.',
      'c3 Nf6 d3 d6 O-O': '6.O-O gets your king safe. Re1, Nbd2 and Bb3 come next; push d4 later when ready.',
      'c3 Nf6 d4': '5.d4 claims the centre. After 5...exd4, 6.e5 kicks the knight or 6.cxd4 keeps two centre pawns.',
      'c3 Nf6 d4 exd4': '5...exd4 takes. 6.O-O or 6.e5 are best; 6.cxd4 lets ...Nxe4 take your e4 pawn.',
      'c3 Nf6 d4 exd4 e5': "6.e5 kicks the knight. Black's best answer is 6...d5, which hits your bishop back.",
      'c3 d6': '4...d6 holds e5. d4 still comes; h3 first keeps the bishop off g4.',
      'c3 d6 d4': '5.d4 hits e5 and builds a centre with pawns on c3, d4 and e4. Castle next.',
      d3: '4.d3 keeps things slow. Castle, c3 and d4 later.',
      'd3 Bc5': '4...Bc5 gives a Giuoco Pianissimo where Black has spent a move on ...h6. c3 and O-O next.',
      'd3 Bc5 Be3': "5.Be3 offers to trade Black's best bishop. If ...Bxe3 fxe3, your f-file opens.",
      'd3 Bc5 Be3 Bxe3': '5...Bxe3 trades. Take back 6.fxe3 at once: the pawn guards d4 and f4, and the f-file opens for your rook.',
      'd3 Bc5 Be3 Bxe3 fxe3': '6.fxe3 recaptures. After you castle, your f1 rook aims up the f-file, which no white pawn blocks.',
      'd3 Bc5 Nc3': '5.Nc3 brings a knight out and eyes d5. Later Na4 or Be3 can swap off the c5 bishop.',
      'd3 Bc5 Nc3 Nf6 h3': "6.h3 keeps Black's bishop off g4, where it would pin your knight to the queen. Castle next.",
      'd3 Bc5 Nc3 Nf6 h3 O-O O-O a6': "7...a6 gives the c5 bishop a retreat on a7, so Na4 can't trade it off. Be3 still offers a swap.",
      'd3 Nf6': '4...Nf6 hits e4, but your d3 pawn guards it. c3 and O-O come next, then d4 later.',
      d4: "4.d4 hits e5 at once, before Black's pieces are out.",
      'd4 Bd6': '4...Bd6 holds e5 but blocks the d7 pawn, so the c8 bishop is stuck. Taking on e5 leaves you clearly better.',
      'd4 Nf6': "4...Nf6 is a mistake: 5.Nxe5 wins a pawn, and Black's tries to win it back fail.",
      'd4 Nf6 Nxe5': '5.Nxe5 grabs a pawn and eyes f7 with knight and bishop. If ...Nxe5 dxe5, the f6 knight is attacked.',
      'd4 Nf6 Nxe5 Nxe5': '5...Nxe5 trades. Take back 6.dxe5: the pawn hits the f6 knight.',
      'd4 Nf6 Nxe5 Nxe5 dxe5': '6.dxe5 attacks the f6 knight. If it takes on e4, Bxf7+ then Qd5+ picks it up with check.',
      'd4 Nf6 Nxe5 Nxe5 dxe5 Nxe4': '6...Nxe4 grabs a pawn, but the knight is loose: Bxf7+ and Qd5+ wins it, leaving you a pawn up.',
      'd4 Nf6 Nxe5 Nxe5 dxe5 Nxe4 Bxf7+': '7.Bxf7+ gives the bishop to drag the king to f7, where Qd5+ will check it and hit the e4 knight.',
      'd4 Nf6 Nxe5 Nxe5 dxe5 Nxe4 Bxf7+ Kxf7': '7...Kxf7 takes. Now 8.Qd5+ checks and attacks the loose e4 knight at the same time.',
      'd4 Nf6 Nxe5 Nxe5 dxe5 Nxe4 Bxf7+ Kxf7 Qd5+': '8.Qd5+ checks and attacks the e4 knight. After the king moves, Qxe4 leaves you a pawn up.',
      'd4 Nf6 Nxe5 Nxe5 dxe5 Nxe4 Bxf7+ Kxf7 Qd5+ Ke8': "8...Ke8. Take the knight with 9.Qxe4: you are a pawn up, and Black's king can never castle.",
      'd4 d6': '4...d6 holds e5. After 5.dxe5 dxe5 6.Qxd8+, Black must take with the king or let e5 fall.',
      'd4 d6 dxe5': '5.dxe5 takes. If 5...dxe5?, 6.Qxd8+ wins a pawn whichever way Black takes back.',
      'd4 exd4': '4...exd4 gives up the centre. 5.Nxd4 recaptures with a strong central knight.',
      'd4 exd4 Nxd4': "5.Nxd4 takes back with a central knight. You lead in development: ...h6 did nothing for Black's pieces.",
      'd4 exd4 Nxd4 Ne5': '5...Ne5 attacks your bishop. Drop it back to b3 or e2; later f4 can kick the knight away.',
      'd4 exd4 Nxd4 Ne5 Bb3': '6.Bb3 keeps your bishop aimed at f7. Later f4 can chase the e5 knight.',
      'd4 exd4 Nxd4 Ne5 Bb3 Bc5': '6...Bc5 eyes your d4 knight, which your queen guards. Bring out Nc3 and Be3 to back it up.',
      'd4 exd4 Nxd4 Nf6': '5...Nf6 hits e4. Guard it with 6.Nc3, bringing another piece out.',
      'd4 exd4 Nxd4 Nxd4': '5...Nxd4 trades knights. 6.Qxd4 centralises your queen; the c6 knight that could have hit it is gone.',
      'd4 exd4 Nxd4 Nxd4 Qxd4': 'Your queen rules the centre. Develop fast with Nc3 and Be3 or Bf4, then castle.',
      'd4 exd4 Nxd4 Nxd4 Qxd4 Nf6': '6...Nf6 allows 7.e5, kicking the knight to h7 on the edge: d5, e4 and g4 are all covered.',
      'd4 exd4 Nxd4 Nxd4 Qxd4 Nf6 e5': '7.e5 kicks the knight, whose best square is now h7 on the edge. Get Nc3 out and castle.',
      'd4 exd4 Nxd4 Nxd4 Qxd4 d6': '6...d6 frees the c8 bishop. Get Nc3 and Be3 or Bf4 out, then castle; your queen in the middle is strong.',
      'd4 exd4 c3': "5.c3 offers a pawn for quick piece play. 5...Nf6 is Black's best answer, hitting e4; 5.Nxd4 was the simple way.",
    },
  },
  {
    id: 'paris-defence',
    name: 'Paris Defence',
    lines: [`${IT} d6`],
    plan: '3...d6 holds e5 but blocks the f8 bishop. Aim for c3 and d4; if Black pins with ...Bg4, h3 asks it to decide.',
    notes: {
      Nc3: '4.Nc3 develops and eyes d5. Watch for ...Bg4 pinning your knight.',
      'Nc3 Bg4': "4...Bg4 pins your knight. 5.h3: if 5...Bh5, 6.Nxe5 wins a pawn, as ...Bxd1 runs into Legal's mate.",
      'Nc3 Bg4 h3': '5.h3 asks the bishop: take on f3 and give you the bishop pair, or retreat to h5.',
      'Nc3 Bg4 h3 Bxf3': '5...Bxf3 gives up the bishop pair. 6.Qxf3 develops your queen with an eye on f7.',
      'O-O': "4.O-O gets your king safe. Next d4 opens the centre while Black's pieces are still at home.",
      c3: '4.c3 prepares d4 for a big centre.',
      d3: '4.d3 keeps things calm. Watch for ...Be6 offering a trade of your strong bishop.',
      'd3 Be6': '4...Be6 challenges your bishop. Bxe6 fxe6 gives Black doubled pawns but an open f-file.',
      'd3 Nf6 Ng5': "5.Ng5 attacks f7 with knight and bishop. 5...d5 is Black's only good answer; other moves lose a pawn.",
      d4: '4.d4 opens the centre. After 4...exd4 5.Nxd4 your pieces become very active.',
      'd4 Bg4': "4...Bg4 pins your knight to the queen, so it can't safely take on e5. 5.h3 asks the bishop at once.",
      'd4 Bg4 h3': '5.h3 asks the bishop to choose. If ...Bxf3, Qxf3 brings your queen out with an eye on f7.',
      h3: '4.h3 stops ...Bg4 pinning your knight. c3 and d4, or d3, follow.',
      'h3 Be6': '4...Be6 offers a bishop trade. Take it: Bxe6 fxe6 leaves Black with two pawns stacked on the e-file.',
      'h3 Be7': '4...Be7 is modest: the bishop only prepares castling. 5.d4 hits e5 straight away.',
      'h3 Nf6': '4...Nf6 leaves f7 thin: 5.Ng5 attacks it twice, and Black must answer 5...d5.',
    },
  },
  {
    id: 'blackburne-shilling',
    name: 'Blackburne Shilling Gambit',
    lines: [`${IT} Nd4`],
    plan: '3...Nd4 sets a trap: 4.Nxe5? Qg5 hits the knight and g2. Trade with 4.Nxd4 exd4, then castle and play c3.',
    notes: {
      Nxd4: '4.Nxd4 trades knights and avoids the trap. After 4...exd4, castle and play c3 to challenge d4.',
      'Nxd4 exd4': '4...exd4 leaves Black a pawn on d4. Castle and play c3 to break it up.',
      'Nxd4 exd4 O-O': '5.O-O puts your king in safety. Next c3 attacks the d4 pawn, and your pieces get out first.',
      'Nxd4 exd4 Qf3': '5.Qf3 threatens Qxf7 mate. Black blocks with 5...Nf6 or 5...Qf6.',
      'Nxd4 exd4 c3': '5.c3 strikes at d4 at once. If ...dxc3, Nxc3 gets your knight out quickly.',
      'Nxd4 exd4 d3': '5.d3 keeps things solid. Castle and play c3 to undermine the d4 pawn.',
      'Nxd4 exd4 d3 Nf6': '5...Nf6 brings a knight out. Castle, then c3 to break up the d4 pawn.',
      Nxe5: '4.Nxe5 walks into the trap: 4...Qg5 attacks the knight and g2 at once.',
      'Nxe5 Qg5': '4...Qg5 hits e5 and g2. Never take f7: 5.Nxf7 Qxg2 6.Rf1 Qxe4+ 7.Be2 Nf3 is mate.',
      'O-O': '4.O-O ignores the knight. ...Nxf3+ Qxf3 only helps your development.',
      c3: '4.c3 kicks the knight. If 4...Nxf3+ 5.Qxf3, your queen joins the game.',
    },
  },
  {
    id: 'rousseau-gambit',
    name: 'Rousseau Gambit',
    lines: [`${IT} f5`],
    plan: "3...f5 hits e4 but opens the diagonal to Black's king. Strike with 4.d4 while Black is behind in development.",
    notes: {
      d3: '4.d3 keeps e4 safe. Ng5 can then jump into f7 or e6, squares ...f5 has weakened.',
      'd3 Bc5': '4...Bc5 develops. Castle or play Nc3; 5.Ng5 threatens a fork on f7, but 5...f4 holds.',
      'd3 Bc5 O-O': '5.O-O tucks your king away. Ng5 can still aim at f7, which ...f5 left empty.',
      'd3 Bc5 O-O f4': '5...f4 leaves e5 loose. 6.Nxe5 wins a pawn: if ...Nxe5, Qh5+ and Qxc5 picks up the bishop.',
      'd3 Bc5 O-O f4 Nxe5': '6.Nxe5 grabs a pawn. If 6...Nxe5, 7.Qh5+ checks, and next you take whichever piece Black leaves loose.',
      'd3 Bc5 O-O f4 Nxe5 Bxf2+': '6...Bxf2+ is a desperate try. Take with 7.Rxf2, keeping your king tucked away; you are a piece up.',
      'd3 Bc5 O-O f4 Nxe5 Bxf2+ Rxf2': "7.Rxf2 recaptures. You are a piece up, and the e8-h5 diagonal to Black's king is open.",
      'd3 Bc5 O-O f4 Nxe5 Bxf2+ Rxf2 Nxe5': "7...Nxe5 levels material, but Black's king is wide open: 8.Qh5+ wins more.",
      'd3 Bc5 O-O f4 Nxe5 Bxf2+ Rxf2 Nxe5 Qh5+': '8.Qh5+ uses the diagonal ...f5 opened. After 8...Ng6, Bxg8 and Qxh7 wins more material.',
      'd3 Bc5 O-O f4 Nxe5 Bxf2+ Rxf2 Nxe5 Qh5+ Ng6': '8...Ng6 blocks. 9.Bxg8 Rxg8 10.Qxh7 then attacks the rook and the g6 knight at once.',
      'd3 Nf6': "4...Nf6 hits e4, but d3 guards it. Castle, then Nc3: Black's king has lost the shelter of its f-pawn.",
      'd3 f4': '4...f4 blocks your c1 bishop but ignores the centre. 5.d4 hits e5 at once.',
      d4: '4.d4 hits e5 and opens lines toward the weakened king.',
      'd4 exd4': '4...exd4 opens the centre. 5.Nxd4 recaptures with a strong central knight.',
      'd4 fxe4': '4...fxe4 grabs a pawn. 5.Nxe5 hits the c6 knight and readies Qh5+ against the weakened king.',
      'd4 fxe4 Nxe5': "5.Nxe5 attacks c6 and prepares Qh5+. Black's king has no f-pawn to shelter it.",
      'd4 fxe4 Nxe5 Nxe5': "5...Nxe5 trades knights. Take back 6.dxe5: your queen and bishop then aim at Black's open king.",
      'd4 fxe4 Nxe5 Nxe5 dxe5': "6.dxe5 levels material, and Black's king has lost its cover; you are clearly better.",
    },
  },
];

const CARO_KANN: Family[] = [
  {
    id: 'caro-kann',
    name: 'Caro-Kann Defence',
    lines: [''],
    plan: null,
    notes: {
      [CK]: '1...c6 prepares ...d5. If White takes on d5, you recapture with the c-pawn and keep a pawn in the centre.',
      [`${CK} d4`]: '2.d4 builds the ideal centre. Strike at it now with 2...d5.',
      [`${CK} d4 d5`]: '2...d5 hits e4. White must defend it with Nc3, Nd2 or f3, push past with e5, or exchange on d5.',
      [`${CK} d4 d5 Nc3`]: "3.Nc3 defends e4 with a piece. 3...dxe4 trades off White's centre pawn for free development.",
      [`${CK} d4 d5 Nd2`]: '3.Nd2 defends e4 and keeps c3 free for a pawn. 3...dxe4 4.Nxe4 leads to the same positions as 3.Nc3.',
      [`${CK} d4 d5 Nc3 dxe4`]: '3...dxe4 gives up the centre on purpose: you get easy development and no weaknesses.',
      [`${CK} d4 d5 Nd2 dxe4`]: '3...dxe4 gives up the centre for easy development. White takes back with the knight.',
      [`${CK} d4 d5 exd5`]: '3.exd5 releases the tension. Recapture with 3...cxd5 to keep a pawn on d5.',
      [`${CK} Qf3`]: '2.Qf3 brings the queen out early. 2...d5 hits e4, and ...Bg4 can later gain time on the queen.',
      [`${CK} Qf3 d5`]: '2...d5 hits e4. If 3.exd5 cxd5, your pawn on d5 controls the centre.',
      [`${CK} Qh5`]: '2.Qh5 is premature. 2...d5 strikes the centre, and ...Nf6 will gain time on the queen.',
      [`${CK} Qh5 d5`]: '2...d5 hits e4. If 3.exd5 cxd5, ...Nf6 develops with gain of time.',
      [`${CK} f4`]: '2.f4 grabs kingside space. 2...d5 hits e4 straight away.',
      [`${CK} f4 d5`]: '2...d5 hits e4. If 3.exd5 cxd5, develop with ...Nc6, ...Nf6 and ...Bg4.',
      [`${CK} e5`]: '2.e5 grabs space at once. 2...d5 gives an Advance where White has not played d4 yet.',
      [`${CK} e5 d5`]: '2...d5 claims the centre. If d4, play ...Bf5 and ...e6 as in the Advance; ...c5 also hits back.',
      [`${CK} f4 d5 e5`]: '3.e5 gains space, Advance style. Play ...Bf5 and ...e6, then ...c5.',
      [`${CK} f4 d5 e5 Bf5`]: '3...Bf5 develops outside the pawn chain. ...e6 and ...c5 follow.',
      [`${CK} f4 d5 e5 Bf5 Nf3`]: '4.Nf3 develops. Continue with ...e6, ...c5 and ...Nc6.',
      [`${CK} Qf3 d5 exd5`]: '3.exd5 trades. Take back with 3...cxd5 to keep a pawn in the centre.',
      [`${CK} Qf3 d5 exd5 cxd5`]: '3...cxd5 gives you the centre pawn. Develop with ...Nf6 and ...Nc6; ...Bg4 can hit the queen.',
      [`${CK} d4 d5 Nc3 a6`]: '3...a6 is a waiting move that prepares ...b5. The usual 3...dxe4 is simpler.',
      [`${CK} d4 d5 Nc3 e6`]: '3...e6 is solid but shuts in your light-squared bishop; 3...dxe4 is the main move.',
      [`${CK} d4 d5 Nc3 dxe4 f3`]: '4.f3 gambits a pawn. Take it: after 4...exf3 5.Nxf3, develop with ...Nf6 and ...Bf5 or ...Bg4.',
      [`${CK} d4 d5 Nf3`]: '3.Nf3 leaves e4 without a defender: 3...dxe4 takes it and attacks the knight.',
    },
  },
  {
    id: 'caro-kann-main-line',
    name: 'Main Line',
    lines: [CK_MAIN],
    plan: 'The e4 knight is centralised, but you have no weaknesses. Choose your set-up: 4...Bf5, 4...Nd7 or 4...Nf6.',
    notes: {},
  },
  {
    id: 'caro-kann-classical',
    name: 'Classical Variation',
    lines: [`${CK_MAIN} Bf5`],
    plan: '4...Bf5 gets your bishop out before ...e6. Expect Ng3 and h4: answer with ...Bg6, ...h6, ...Nd7 and ...e6.',
    notes: {
      Bd3: '5.Bd3 leaves d4 loose: 5...Qxd4 wins a pawn. 5...Bxe4 6.Bxe4 Nf6 is the calm alternative.',
      'Bd3 Qxd4': '5...Qxd4 wins a pawn. After 6.Nf3, drop the queen back to d8, then play ...e6 and ...Nd7.',
      Nc3: '5.Nc3 retreats the knight. Continue with ...e6, ...Nf6 and ...Nd7.',
      Ng3: '5.Ng3 hits your bishop. Drop back with 5...Bg6, keeping it on the h7-b1 diagonal.',
      'Ng3 Bg6': '5...Bg6 keeps the bishop active. White often pushes h4 and h5 to chase it.',
      'Ng3 Bg6 Nf3': "6.Nf3 develops. 6...Nd7 keeps White's knight off e5.",
      'Ng3 Bg6 Nf3 Nd7': '6...Nd7 guards e5. Next ...Ngf6 and ...e6 finish a solid set-up.',
      'Ng3 Bg6 Nf3 e6': "6...e6 frees your dark-squared bishop. If Bd3, trading on d3 removes White's best attacker.",
      'Ng3 Bg6 f4': '6.f4 threatens f5, hitting the bishop. 6...e6 is the answer: f5 can then be met by ...exf5.',
      'Ng3 Bg6 h4': '6.h4 threatens h5, hitting your bishop. Play 6...h6 so the bishop can drop to h7.',
      'Ng3 Bg6 h4 h6': '6...h6 makes room on h7. After h5 the bishop retreats there and stays on the long diagonal.',
      'Ng3 Bg6 h4 h6 Nf3': '7.Nf3 develops. 7...Nd7 stops Ne5 and prepares ...Ngf6.',
      'Ng3 Bg6 h4 h6 Nf3 Nd7': '7...Nd7 guards e5. White often plays 8.h5 Bh7 9.Bd3, offering a bishop trade.',
      'Ng3 Bg6 h4 h6 h5': '7.h5 hits the bishop. 7...Bh7 keeps it on its diagonal.',
      'Ng3 Bg6 h4 h6 h5 Bh7': '7...Bh7. White will offer a trade with Bd3; take it and your pawns stay healthy.',
      f3: '5.f3 prepares g4 against your bishop. 5...e6 makes room; after g4, ...Bg6 keeps it on the diagonal.',
      'f3 e6': '5...e6 gives the bishop room and frees your other bishop. If g4, drop back to g6.',
    },
  },
  {
    id: 'caro-kann-karpov',
    name: 'Karpov Variation',
    lines: [`${CK_MAIN} Nd7`],
    plan: '4...Nd7 prepares ...Ngf6, so a trade on f6 is met by the knight and your pawns stay healthy. Then ...e6 or ...Bf5.',
    notes: {
      Bc4: '5.Bc4 eyes f7. Play 5...Ngf6; if Ng5, ...e6 shuts the bishop out.',
      Nf3: '5.Nf3 develops. 5...Ngf6 challenges the e4 knight; take back with the knight if White trades.',
      'Nf3 Ngf6': '5...Ngf6 offers the trade. After Nxf6+ Nxf6 your structure is perfect.',
      Ng5: '5.Ng5 eyes f7 and e6. 5...Ngf6 6.Bd3 e6 is the solid answer.',
      Qe2: '5.Qe2 sets a trap: 5...Ngf6?? 6.Nd6 is smothered mate. Play 5...Ndf6 instead.',
    },
  },
  {
    id: 'caro-kann-nf6',
    name: '4...Nf6 Variation',
    lines: [`${CK_MAIN} Nf6`],
    plan: '4...Nf6 challenges the e4 knight. After 5.Nxf6+, ...exf6 gives quick development, ...gxf6 an open g-file.',
    notes: {
      Ng3: '5.Ng3 avoids the trade. Develop freely with ...e6, ...Bd6 or ...Bg4.',
      Ng5: '5.Ng5 moves the knight again. Develop with ...Bf5 or ...Bg4; ...h6 sends it back to f3.',
      'Nxf6+': '5.Nxf6+ trades. 5...exf6 opens lines for your bishop and queen; 5...gxf6 is sharper.',
      'Nxf6+ exf6': '5...exf6 gives easy development: ...Bd6, ...O-O and ...Re8. White has the healthier pawns for an endgame.',
      'Nxf6+ exf6 Bc4': '6.Bc4 aims at f7. ...Bd6, ...O-O and ...Re8 develop quickly.',
      'Nxf6+ exf6 Nf3': '6.Nf3 develops. Continue with ...Bd6, ...O-O and ...Re8 for quick play on the e-file.',
      'Nxf6+ exf6 Nf3 Bd6': '6...Bd6 develops and eyes h2. Castle next and put a rook on e8.',
      'Nxf6+ exf6 Nf3 Bd6 Bc4': '7.Bc4 aims at f7. Castle short and bring a rook to e8.',
      'Nxf6+ exf6 Nf3 Bd6 Bc4 O-O': '7...O-O tucks your king away. ...Re8 and ...Bf5 or ...Bg4 come next.',
      'Nxf6+ gxf6': '5...gxf6 opens the g-file for your rook. Your king often stays in the centre or goes queenside.',
    },
  },
  {
    id: 'caro-kann-advance',
    name: 'Advance Variation',
    lines: [CK_ADVANCE],
    plan: 'White grabs space with e5. Get your bishop out with ...Bf5 before ...e6, then hit the pawn chain with ...c5.',
    notes: {
      Bf5: '3...Bf5 develops the bishop outside the pawn chain before ...e6 shuts it in.',
      'Bf5 Bd3': '4.Bd3 offers a bishop trade. 4...Bxd3 5.Qxd3 e6 is comfortable: you swap off your problem bishop.',
      'Bf5 Bd3 Bxd3': '4...Bxd3 trades off your problem bishop. White takes back with the queen; ...e6 follows.',
      'Bf5 Bd3 Bxd3 Qxd3': '5.Qxd3 recaptures. 5...e6 next: with the light bishops gone, your pawns on light squares are no problem.',
      'Bf5 Bd3 Bxd3 Qxd3 e6': '5...e6 completes the chain. Next ...c5, ...Qb6 and ...Nc6 hit d4.',
      'Bf5 Bd3 Bxd3 Qxd3 e6 Nf3': '6.Nf3 supports d4. Strike with 6...c5, or prepare it with ...Qb6.',
      'Bf5 Bd3 Bxd3 Qxd3 e6 Nf3 c5': '6...c5 attacks the chain at its base. ...Nc6 and ...Qb6 add pressure to d4.',
      'Bf5 Nc3': '4.Nc3 prepares g4 to chase your bishop. Play 4...e6 and be ready for ...Bg6 and ...c5.',
      'Bf5 Nc3 e6': '4...e6 opens your other bishop. If g4, drop back to g6 and strike with ...c5.',
      'Bf5 c3': '4.c3 supports d4. Continue with ...e6, ...Nd7, ...Ne7 and ...c5.',
      'Bf5 f4': '4.f4 props up e5 but blocks the c1 bishop. Play ...e6 and ...c5 against the chain.',
      'Bf5 f4 e6': '4...e6 opens your dark-squared bishop. Next ...c5 hits d4.',
      'Bf5 f4 e6 Nf3': '5.Nf3 holds d4. Strike with ...c5 and ...Nc6.',
      'Bf5 g4 Bg6': '4...Bg6 keeps the diagonal. If h4, answer ...h5 at once: it hits g4 and stops h5.',
      'Bf5 h4': '4.h4 threatens g4 and h5 against the bishop. 4...h5 stops it, at the cost of the g5 square.',
      'Bf5 h4 h5': '4...h5 halts the h-pawn. White gets g5 for a piece, but your bishop stays free.',
      c5: '3...c5 hits d4 at once. It costs a tempo, but the chain is challenged before White is ready.',
      'c5 Nf3': '4.Nf3 supports d4. ...Bg4 pins the knight, and ...Nc6 adds pressure on d4.',
      'c5 Nf3 Bg4': '4...Bg4 pins the knight that guards d4. ...cxd4 and ...Nc6 follow.',
      'c5 Nf3 Nc6': '4...Nc6 piles on d4. ...Bg4 next pins its defender on f3.',
      'c5 c3': '4.c3 supports d4. Develop with ...Nc6 and ...Bf5 or ...Bg4, pressing d4.',
      'c5 c3 Nc6': '4...Nc6 piles on d4. Next ...Bf5 or ...Bg4, and ...Qb6.',
      'c5 c3 Nc6 Nf3': '5.Nf3 holds d4. ...Bg4 pins the defender; ...cxd4 and ...Qb6 add pressure.',
      'c5 c3 cxd4': '4...cxd4 opens the c-file. After 5.cxd4, ...Nc6 and ...Bf5 or ...Bg4 hit d4.',
      'c5 c3 cxd4 cxd4': '5.cxd4 recaptures. The c-file is open: ...Nc6, ...Bf5 and ...Rc8 use it.',
      'c5 c4': '4.c4 hits d5. 4...cxd4 or 4...Nc6 hits back at d4; if Qxd4, ...Nc6 gains time on the queen.',
      'c5 dxc5': '4.dxc5 gives up the base of the chain. ...e6 and ...Bxc5 win the pawn back with good development.',
      'c5 dxc5 Nc6': '4...Nc6 develops and prepares ...e6 and ...Bxc5, winning back the pawn.',
      'c5 dxc5 Nc6 Nf3': '5.Nf3 guards e5. ...Bg4 pins the knight that holds it.',
      'c5 dxc5 Nc6 Nf3 Bg4': '5...Bg4 pins the knight that guards e5. ...e6 and ...Bxc5 regain the pawn.',
      e6: '3...e6 shuts in your light-squared bishop. It is playable, but ...Bf5 first is the usual order.',
      'e6 Nf3': '4.Nf3 supports d4. Strike with ...c5 to free your game.',
      'e6 Nf3 c5': '4...c5 hits d4. ...Nc6 and ...Qb6 add pressure; your c8 bishop can come out via d7.',
    },
  },
  {
    id: 'caro-kann-short',
    name: 'Advance: Short System',
    lines: [`${CK_ADVANCE} Bf5 Nf3`],
    plan: 'White plays Nf3, Be2, O-O and c3. Build with ...e6, ...c5, ...Nc6 and ...Ne7, and keep pressing d4.',
    notes: {
      e6: '4...e6 opens your dark-squared bishop; the light-squared one is already outside the chain.',
      'e6 Bd3': '5.Bd3 offers a bishop trade. Take: after ...Bxd3 Qxd3 your remaining bishop is the good one.',
      'e6 Bd3 Bxd3': '5...Bxd3 trades off your problem bishop. After 6.Qxd3, hit the chain with ...c5.',
      'e6 Bd3 Bxd3 Qxd3': '6.Qxd3 recaptures. Now ...c5 strikes at d4, with ...Nc6 and ...Qb6 to follow.',
      'e6 Be2': '5.Be2 prepares O-O. Strike with 5...c5, or play ...Nd7 and ...Ne7 first.',
      'e6 Be2 c5': '5...c5 hits d4. White supports it with Be3 or c3; your knight joins with ...Nc6.',
      'e6 Nc3': '5.Nc3 develops. ...c5 still hits d4, and ...Nc6 adds pressure.',
      'e6 c3': '5.c3 props up d4. Play ...c5 anyway, or ...Nd7 and ...Ne7 to prepare it.',
      'e6 h3': '5.h3 prepares g4. If g4, the bishop drops to g6; strike the centre with ...c5.',
    },
  },
  {
    id: 'caro-kann-bayonet',
    name: 'Advance: Bayonet Attack',
    lines: [`${CK_ADVANCE} Bf5 Nc3 e6 g4`, `${CK_ADVANCE} Bf5 g4`],
    plan: 'White chases your bishop with g4 and h4. Tuck it away on g6 or d7, then hit the centre with ...c5.',
    notes: {
      Bg6: '5...Bg6 keeps the bishop on its diagonal. Next ...c5 hits d4 before the kingside storm lands.',
      'Bg6 Nge2': '6.Nge2 prepares h4 and Nf4. Strike now with 6...c5.',
    },
  },
  {
    id: 'caro-kann-exchange',
    name: 'Exchange Variation',
    lines: [`${CK} d4 d5 exd5 cxd5`],
    plan: 'The centre is fixed, so piece play decides. Develop ...Nc6, ...Nf6 and ...Bg4 or ...Bf5; later ...b5-b4 can hit c3.',
    notes: {
      'Bb5+': '4.Bb5+ checks. Block with ...Nc6 or ...Bd7; both develop.',
      Bd3: '4.Bd3 aims at h7 and keeps your bishop off f5 for now. Develop with ...Nc6 and ...Nf6; ...Bg4 works well.',
      'Bd3 Nc6': '4...Nc6 hits d4. White usually guards it with c3.',
      'Bd3 Nc6 Nf3': '5.Nf3 develops. 5...Bg4 pins it and adds pressure on d4.',
      'Bd3 Nc6 Nf3 Bg4': '5...Bg4 pins the knight that guards d4. c3 holds; ...e6 and ...Nf6 complete your set-up.',
      'Bd3 Nc6 c3': '5.c3 holds d4. Continue with ...Nf6 and ...Bg4, pinning the knight once it lands on f3.',
      'Bd3 Nc6 c3 Nf6': '5...Nf6 develops and guards h7. ...Bg4 comes next, unless White stops it with h3.',
      'Bd3 Nc6 c3 Nf6 h3': '6.h3 stops ...Bg4. 6...e5 hits back in the centre; 6...e6 and ...Bd6 is calmer.',
      'Bd3 Nc6 c3 Nf6 h3 e5': '6...e5 opens the game. After 7.dxe5 Nxe5 your d5 pawn is isolated but your pieces are active.',
      'Bd3 Nc6 c3 Nf6 h3 e5 dxe5 Nxe5': '7...Nxe5 centralises. Watch the e-file: Qe2 can pin your knight to the king.',
      'Bd3 Nf6': '4...Nf6 develops and guards h7. ...Nc6 and ...Bg4 come next.',
      'Bd3 Nf6 h3': '5.h3 rules out ...Bg4. Develop with ...Nc6 and ...e6 or ...e5.',
      'Bd3 e6': '4...e6 is solid but locks in your light-squared bishop. ...Bd6, ...Nf6 and ...O-O follow.',
      Bf4: '4.Bf4 develops actively. ...Nc6 and ...Qb6 can hit d4 and b2.',
      Nc3: '4.Nc3 develops. ...Nf6 and ...Nc6 hit back at d4, then ...Bg4 or ...Bf5.',
      'Nc3 Bf5': '4...Bf5 develops outside the pawn chain. ...e6 and ...Nf6 make d5 secure.',
      'Nc3 Nc6': '4...Nc6 hits d4. ...Nf6 and ...Bg4 or ...Bf5 next.',
      'Nc3 Nf6': '4...Nf6 guards d5. ...Nc6 and ...Bg4 next; ...e6 keeps it solid.',
      'Nc3 Nf6 Nf3': '5.Nf3 develops. 5...Nc6 hits d4 and ...Bg4 pins its defender.',
      'Nc3 Nf6 Nf3 Bg4': '5...Bg4 pins the knight that guards d4. If h3, take on f3 and play ...e6.',
      'Nc3 Nf6 Nf3 Bg4 h3': '6.h3 asks the bishop. ...Bxf3 Qxf3 e6 gives a solid game.',
      'Nc3 Nf6 Nf3 Bg4 h3 Bxf3': '6...Bxf3 removes a defender of d4. After Qxf3, ...e6 and ...Nc6 follow.',
      'Nc3 Nf6 Nf3 Bg4 h3 Bxf3 Qxf3': '7.Qxf3 recaptures, hitting d5. Play ...e6 to hold d5 firmly.',
      'Nc3 Nf6 Nf3 Nc6': "5...Nc6 hits d4. Bb5 may pin it; ...Bg4 pins White's knight in return.",
      'Nc3 Nf6 Nf3 Nc6 Bb5': '6.Bb5 pins your knight. ...Bg4 pins back, or ...e6 and ...Bd6 develop.',
      'Nc3 Nf6 Nf3 Nc6 Bb5 Bg4': "6...Bg4 pins White's knight in return. If Bxc6+, bxc6 gives you a solid centre.",
      Nf3: '4.Nf3 develops. ...Nc6, ...Nf6 and ...Bg4 give you easy play.',
      c3: '4.c3 supports d4 early. Develop freely: ...Nc6, ...Nf6 and ...Bf5.',
    },
  },
  {
    id: 'caro-kann-panov',
    name: 'Panov Attack',
    lines: [`${CK} d4 d5 exd5 cxd5 c4`],
    plan: 'White accepts an isolated d-pawn for activity. Blockade d5, develop ...Nf6, ...e6 and ...Nc6, and trade pieces.',
    notes: {
      Nf6: '4...Nf6 develops and adds a defender to d5. Next ...e6 or ...Nc6.',
      'Nf6 Nc3': '5.Nc3 piles on d5. Choose ...e6 for a solid game or ...Nc6 for active play.',
      'Nf6 Nc3 Nc6': "5...Nc6 develops and hits d4, White's weak spot.",
      'Nf6 Nc3 Nc6 Nf3': '6.Nf3 develops. ...Bg4 pins the knight; ...e6 and ...Be7 are solid.',
      'Nf6 Nc3 e6': '5...e6 shores up d5. Your dark-squared bishop goes to e7 or b4.',
      e6: '4...e6 shores up d5 and opens your dark-squared bishop.',
    },
  },
  {
    id: 'caro-kann-fantasy',
    name: 'Fantasy Variation',
    lines: [`${CK} d4 d5 f3`],
    plan: "3.f3 props up e4 but weakens White's king. Hit the centre: ...e6 and ...c5, or ...dxe4 and ...e5.",
    notes: {
      Qb6: "3...Qb6 hits d4 and b2 at once, while White's knight cannot use f3.",
      dxe4: "3...dxe4 4.fxe4 e5 hits d4 at once while White's king is airy.",
      'dxe4 fxe4': '4.fxe4 gives White a big centre. Hit it now with 4...e5.',
      'dxe4 fxe4 e5': '4...e5 strikes back at d4, and the open e1-h4 diagonal gives your queen ...Qh4+ ideas.',
      e6: '3...e6 prepares ...c5 to hit d4. If 4.Nc3, ...Bb4 pins the knight and pressures e4.',
    },
  },
  {
    id: 'caro-kann-two-knights',
    name: 'Two Knights Variation',
    lines: [`${CK} Nc3 d5 Nf3`],
    plan: 'Pin the f3 knight with ...Bg4. After h3, take it and build with ...e6 and ...Nf6: a rock-solid set-up.',
    notes: {
      Bg4: '3...Bg4 pins the f3 knight, which guards d4 and e5. h3 usually follows.',
      'Bg4 Be2': '4.Be2 unpins quietly. ...e6, ...Nf6 and ...Nd7 give a solid game.',
      'Bg4 h3': '4.h3 asks the bishop. 4...Bxf3 5.Qxf3 e6 is rock solid; 4...Bh5 keeps the pin.',
      'Bg4 h3 Bh5': '4...Bh5 keeps the pin. If g4, drop back to g6; your bishop stays active.',
      'Bg4 h3 Bxf3': '4...Bxf3 gives up the bishop pair but removes a key defender. Follow with ...e6 and ...Nf6.',
      'Bg4 h3 Bxf3 Qxf3': '5.Qxf3 recaptures. Continue with ...e6 and ...Nf6: White has the bishop pair, you have the solid pawns.',
      dxe4: '3...dxe4 takes the centre pawn. After 4.Nxe4, ...Bf5, ...Nd7 or ...Nf6 work like the main lines.',
      'dxe4 Nxe4': '4.Nxe4 recaptures. Develop as in the main line: ...Bf5 to hit the knight, or ...Nd7 and ...Ngf6.',
      'dxe4 Nxe4 Bf5': '4...Bf5 gains time on the knight. After Ng3 Bg6, continue ...e6 and ...Nf6.',
      'dxe4 Nxe4 Nf6': '4...Nf6 challenges the knight. After 5.Nxf6+ exf6 you get quick development.',
      'dxe4 Nxe4 Nf6 Nxf6+': '5.Nxf6+ trades. Take with the e-pawn for fast development: ...Bd6, ...O-O and ...Re8.',
      'dxe4 Nxe4 Nf6 Nxf6+ exf6': '5...exf6 opens lines for your pieces. Your kingside pawns are doubled but shelter your king well.',
      'dxe4 Nxe4 Nf6 Nxf6+ exf6 d4': '6.d4 reaches the 4...Nf6 main line. Develop with ...Bd6, ...O-O and ...Re8.',
    },
  },
  {
    id: 'caro-kann-nf3',
    name: 'Caro-Kann: 2.Nf3',
    lines: [`${CK} Nf3`],
    plan: '2.Nf3 holds back the d-pawn. Play ...d5 anyway, then pin the knight with ...Bg4 when it helps.',
    notes: {
      d5: "2...d5 hits e4. White's main choices are 3.Nc3, 3.e5, 3.exd5 and 3.d3.",
      'd5 d3': '3.d3 supports e4 quietly. ...Bg4 is natural; 3...dxe4 4.dxe4 Qxd1+ swaps queens.',
      'd5 d3 Bg4': '3...Bg4 pins the knight. ...e6, ...Nf6 and ...Nd7 give a solid set-up.',
      'd5 d3 dxe4': '3...dxe4 opens the d-file. 4.dxe4 allows a queen trade; 4.Ng5 is a gambit aimed at f7 and e4.',
      'd5 d3 dxe4 Ng5': '4.Ng5 gambits a pawn, eyeing e4 and f7. 4...exd3 grabs a second pawn; 4...e5 is simpler.',
      'd5 d3 dxe4 Ng5 exd3': "4...exd3 keeps the extra pawn, but White's pieces get open lines toward your king.",
      'd5 d3 dxe4 Ng5 exd3 Bxd3': '5.Bxd3 eyes h7. Play 5...Nd7 or 5...Qc7; 5...Nf6? 6.Nxf7! wins, as ...Kxf7 Bg6+ drops your queen.',
      'd5 d3 dxe4 dxe4': "4.dxe4 lets you swap queens with 4...Qxd1+, and White's king loses the right to castle.",
      'd5 d4': '3.d4 leaves e4 without a defender: 3...dxe4 takes it and attacks the knight.',
      'd5 d4 dxe4': '3...dxe4 takes the pawn and hits the knight, which must move. ...Bf5 then guards e4.',
      'd5 d4 dxe4 Ng5': '4.Ng5 hits e4 and eyes f7. 4...Bf5 or 4...Nf6 guards the pawn.',
      'd5 e5': "3.e5 gains space. Without d4 played yet, 3...Bg4 pins the knight and weakens White's grip.",
      'd5 e5 Bf5': '3...Bf5 develops outside the chain. ...e6 and ...c5 come next.',
      'd5 e5 Bf5 Nc3 e6 d4': '5.d4 gives an Advance with knights on c3 and f3. Strike now with 5...c5.',
      'd5 e5 Bg4': '3...Bg4 pins the knight that supports e5 and d4. Next ...e6 and ...c5 attack the chain.',
      'd5 e5 Bg4 Be2': '4.Be2 unpins before d4. Take on f3 or play ...e6 and ...c5.',
      'd5 e5 Bg4 d4': '4.d4 makes it an Advance with your bishop on g4. Play ...e6 and ...c5.',
      'd5 e5 Bg4 d4 e6': '4...e6 opens your other bishop. ...c5 comes next, and ...Bxf3 can remove a defender of d4.',
      'd5 e5 Bg4 d4 e6 Be2': '5.Be2 unpins. Strike with 5...c5 and ...Nc6.',
      'd5 e5 c5': '3...c5 hits d4 before White has played it. ...Nc6 and ...Bg4 follow.',
      'd5 exd5': '3.exd5 releases the tension. Take back 3...cxd5 for a pawn on d5 and an open c-file.',
      'd5 exd5 cxd5': '3...cxd5 gives you a solid centre pawn. Develop with ...Nc6, ...Nf6 and ...Bg4.',
      'd5 exd5 cxd5 Bb5+': '4.Bb5+ checks. ...Nc6 develops; ...Bd7 offers a trade of bishops.',
      'd5 exd5 cxd5 Bb5+ Nc6': '4...Nc6 blocks with a developing move. Next ...Nf6 and ...Bg4.',
      'd5 exd5 cxd5 Nc3': '4.Nc3 hits d5. ...Nf6 guards it; then ...Nc6 and ...Bg4.',
      'd5 exd5 cxd5 Nc3 Bf5': '4...Bf5 develops. ...e6 and ...Nf6 make d5 secure.',
      'd5 exd5 cxd5 Nc3 Bg4': '4...Bg4 pins the knight. ...Nf6 and ...e6 next; if h3, take on f3.',
      'd5 exd5 cxd5 Nc3 Nf6': '4...Nf6 guards d5 and develops. Next ...Nc6 and ...Bg4 or ...Bf5.',
      'd5 exd5 cxd5 Nc3 Nf6 d4': '5.d4 sets up an Exchange structure. ...Nc6 hits d4 and ...Bg4 pins the knight that guards it.',
      'd5 exd5 cxd5 Nc3 Nf6 d4 Bf5': '5...Bf5 develops outside the pawn chain. ...e6 and ...Nc6 follow.',
      'd5 exd5 cxd5 c4': '4.c4 hits d5, Panov style. ...Nf6 and ...e6 keep it solid.',
      'd5 exd5 cxd5 d4': '4.d4 reaches an Exchange Variation. ...Nc6, ...Nf6 and ...Bg4 develop with pressure on d4.',
      'd5 exd5 cxd5 d4 Bf5': '4...Bf5 develops the light-squared bishop before ...e6. Next ...Nc6 and ...e6.',
      'd5 exd5 cxd5 d4 Bg4': '4...Bg4 pins the knight that guards d4. ...Nc6 next adds pressure.',
      'd5 exd5 cxd5 d4 Bg4 Bb5+': '5.Bb5+ checks. Block with ...Nc6, developing; h3 may then ask your bishop to decide.',
      'd5 exd5 cxd5 d4 Bg4 Bb5+ Nc6 h3': '6.h3 asks the bishop. ...Bxf3 Qxf3 e6 is solid: your pawns on d5 and e6 hold.',
      'd5 exd5 cxd5 d4 Bg4 Be2': '5.Be2 unpins. Develop with ...Nc6, ...e6 and ...Nf6; ...Bxf3 can come when it helps.',
      'd5 exd5 cxd5 d4 Bg4 Be2 Nc6': '5...Nc6 adds pressure on d4. ...e6 and ...Nf6 complete your set-up.',
      'd5 exd5 cxd5 d4 Bg4 Be2 Nf6': '5...Nf6 develops. If h3, take on f3 or keep the pin with ...Bh5.',
      'd5 exd5 cxd5 d4 Bg4 Nc3': '5.Nc3 hits d5. ...Nf6 guards it; ...e6 makes it rock solid.',
      'd5 exd5 cxd5 d4 Nc6': '4...Nc6 hits d4. If Bb5 pins it, ...Bd7 or ...a6 breaks the pin.',
      'd5 exd5 cxd5 d4 Nc6 Bb5': '5.Bb5 pins your knight. ...Bd7 unpins; ...Bg4 develops and meets Bxc6+ with bxc6.',
      'd5 exd5 cxd5 d4 Nc6 Bb5 Bd7': '5...Bd7 breaks the pin. If Bxc6, take with the bishop and keep your pawns intact.',
      'd5 exd5 cxd5 d4 Nc6 Bb5 Bg4': "5...Bg4 pins White's knight in turn. If Bxc6+ bxc6, your pawns on c6 and d5 hold the centre.",
      'd5 exd5 cxd5 d4 Nc6 Be2': '5.Be2 is quiet. ...Bg4 or ...Bf5 and ...Nf6 give you an easy game.',
      'd5 exd5 cxd5 d4 Nc6 c3': '5.c3 holds d4. ...Bg4 pins the knight and ...Nf6 completes development.',
      'd5 exd5 cxd5 d4 Nf6': '4...Nf6 develops and covers d5 and h7 at once.',
      'd5 exd5 cxd5 d4 Nf6 Nc3': '5.Nc3 hits d5. ...Nc6 or ...e6 guard it, and ...Bg4 pins the f3 knight.',
      'd5 exd5 cxd5 d4 Nf6 c4': '5.c4 makes it a Panov. ...e6 or ...Nc6 keep d5 well guarded.',
    },
  },
  {
    id: 'caro-kann-hillbilly',
    name: 'Hillbilly Attack',
    lines: [`${CK} Bc4`],
    plan: '2...d5 hits the bishop and e4. After 3.exd5 cxd5 the bishop must move again, and you have a free centre.',
    notes: {
      d5: '2...d5 hits both the bishop and e4. White must take on d5 or move the bishop.',
      'd5 Bb3': '3.Bb3 leaves e4 hanging: 3...dxe4 wins a pawn. If 4.Qh5, guard f7 with ...e6 or ...g6.',
      'd5 exd5': '3.exd5 trades. Recapture with 3...cxd5, hitting the bishop again.',
      'd5 exd5 cxd5': '3...cxd5 attacks the bishop and gives you a strong d5 pawn. It goes to b3 or checks on b5.',
      'd5 exd5 cxd5 Bb3': '4.Bb3 keeps the bishop aimed at d5 and f7. Develop with ...Nf6 and ...Nc6, then ...Bf5 or ...Bg4.',
      'd5 exd5 cxd5 Bb3 Bf5': '4...Bf5 develops outside the pawn chain. If Qf3 hits f5 and d5, ...e6 covers both.',
      'd5 exd5 cxd5 Bb3 Nc6': '4...Nc6 develops and eyes d4 and e5. ...Nf6 and ...Bf5 or ...Bg4 follow.',
      'd5 exd5 cxd5 Bb3 Nf6': '4...Nf6 develops and guards d5. Next ...Nc6 and ...Bf5 or ...Bg4.',
      'd5 exd5 cxd5 Bb3 Nf6 d4': '5.d4 gives an Exchange-type centre. ...Nc6 and ...Bg4 hit d4.',
      'd5 exd5 cxd5 Bb3 Nf6 d4 Nc6': '5...Nc6 piles on d4. Next ...Bg4 or ...Bf5; ...e6 keeps d5 solid.',
      'd5 exd5 cxd5 Bb3 e5': '4...e5 grabs the centre, but after 5.d4 exd4 6.Qxd4 your d5 pawn comes under fire.',
      'd5 exd5 cxd5 Bb5+': '4.Bb5+ checks. ...Nc6 develops; ...Bd7 offers a bishop trade.',
      'd5 exd5 cxd5 Bb5+ Bd7': '4...Bd7 blocks and offers a trade. Take back on d7 with the queen or knight and develop.',
      'd5 exd5 cxd5 Bb5+ Nc6': '4...Nc6 blocks with a developing move. If Bxc6+ bxc6, your pawns on c6 and d5 control the centre.',
      'd5 exd5 cxd5 Bb5+ Nc6 Bxc6+': '5.Bxc6+ gives up the bishop pair. Take with the pawn: bxc6 strengthens d5.',
      'd5 exd5 cxd5 Bb5+ Nc6 Bxc6+ bxc6': '5...bxc6 leaves you two bishops and a solid centre. ...Nf6, ...Bf5 or ...Bg4 next.',
      e6: '2...e6 blunts the bishop and prepares ...d5 with extra support.',
    },
  },
  {
    id: 'caro-kann-accelerated-panov',
    name: 'Accelerated Panov',
    lines: [`${CK} c4`],
    plan: '2.c4 hits d5 in advance. Play ...d5 anyway: after the trades on d5, ...Nf6 and ...Nxd5 win the pawn back.',
    notes: {
      d5: '2...d5 strikes at once. White can take with the e- or c-pawn; you will regain the pawn.',
      'd5 cxd5': '3.cxd5 trades. Take back 3...cxd5; after 4.exd5, ...Nf6 regains the pawn.',
      'd5 cxd5 cxd5': '3...cxd5 hits e4. White takes with exd5 or pushes e5.',
      'd5 cxd5 cxd5 e5': '4.e5 gains space, Advance style. Develop with ...Nc6 and ...Bf5; after d4, ...Qb6 hits it.',
      'd5 cxd5 cxd5 exd5': '4.exd5 leaves White a pawn up for now. 4...Nf6 wins it back; 4...Qxd5 lets Nc3 gain time.',
      'd5 exd5': '3.exd5 trades. Take back 3...cxd5; if 4.cxd5, play 4...Nf6 and ...Nxd5.',
      'd5 exd5 cxd5': '3...cxd5 hits c4. If 4.cxd5, 4...Nf6 regains the pawn without bringing your queen out early.',
      'd5 exd5 cxd5 cxd5': '4.cxd5 leaves White a pawn up for now. 4...Nf6 wins it back; 4...Qxd5 lets Nc3 gain time.',
      'd5 exd5 cxd5 cxd5 Nf6': '4...Nf6 attacks d5. White defends with Nc3 or Bb5+, but ...Nxd5 comes soon.',
      'd5 exd5 cxd5 cxd5 Qxd5': '4...Qxd5 regains the pawn, but 5.Nc3 hits the queen and gains time.',
      'd5 exd5 cxd5 cxd5 Qxd5 Nc3': '5.Nc3 hits the queen. Drop it back to d8 or a5 and develop quickly.',
    },
  },
  {
    id: 'caro-kann-d3',
    name: 'Caro-Kann: 2.d3',
    lines: [`${CK} d3`],
    plan: "2.d3 heads for a King's Indian Attack: Nd2, Ngf3, g3, Bg2 and O-O. Take space with ...d5 and ...e5.",
    notes: {
      d5: '2...d5 claims the centre. White is in no hurry, so you can build with ...e5 or ...Bg4.',
      'd5 Nc3': '3.Nc3 adds a defender to e4. 3...dxe4 4.Nxe4 gives a main-line type game; ...d4 gains space instead.',
      'd5 Nd2': '3.Nd2 keeps e4 supported. 3...e5 stakes out the centre.',
      'd5 Nd2 e5': '3...e5 takes your share of the centre. ...Bd6, ...Nf6 and ...O-O follow.',
      'd5 Nf3': '3.Nf3 develops. ...Bg4 pins it, or ...dxe4 offers a queen trade.',
      'd5 exd5': '3.exd5 trades. Take back 3...cxd5 for a strong pawn on d5.',
      'd5 exd5 cxd5': '3...cxd5 gives you more of the centre than White. Develop with ...Nc6, ...Nf6 and ...Bg4.',
    },
  },
  {
    id: 'caro-kann-nc3',
    name: 'Caro-Kann: 2.Nc3',
    lines: [`${CK} Nc3`],
    plan: "2.Nc3 guards e4 and keeps White's options open. After 2...d5, 3.d4 is the main line and 3.Nf3 the Two Knights.",
    notes: {
      d5: '2...d5 hits e4. White can defend with Nf3 or d4, take on d5, or play Qf3.',
      'd5 Qf3': '3.Qf3 defends e4 with the queen. ...d4 kicks the knight and gains space; ...dxe4 and ...Nf6 develop simply.',
      'd5 d4': '3.d4 transposes to the main line. 3...dxe4 4.Nxe4, then choose ...Bf5, ...Nd7 or ...Nf6.',
      'd5 e5': '3.e5 gains space. ...Bf5, ...e6 and ...c5 work as in the Advance.',
      'd5 exd5': '3.exd5 trades. Recapture 3...cxd5 to keep a strong pawn on d5.',
      'd5 exd5 cxd5': '3...cxd5 leaves you the extra centre pawn. Develop with ...Nf6, ...Nc6 and ...Bg4 or ...Bf5.',
      'd5 exd5 cxd5 Nf3': '4.Nf3 develops. ...Nc6, ...Nf6 and ...Bg4 give you easy play.',
      'd5 exd5 cxd5 Nf3 Nc6': '4...Nc6 develops. If d4, ...Bg4 pins its defender.',
      'd5 exd5 cxd5 Nf3 Nc6 d4': '5.d4 gives an Exchange set-up. 5...Bg4 pins the knight that guards d4; ...Nf6 also works.',
      'd5 exd5 cxd5 Nf3 Nc6 d4 Bg4': '5...Bg4 pins the knight. Be2 unpins; then ...e6 and ...Nf6.',
      'd5 exd5 cxd5 Nf3 Nc6 d4 Bg4 Be2': '6.Be2 unpins. ...e6, ...Nf6 and ...Bd6 complete a solid set-up.',
      'd5 exd5 cxd5 d4': '4.d4 gives an Exchange set-up. ...Nf6, ...Nc6 and ...Bf5 or ...Bg4.',
      'd5 f3': '3.f3 holds e4 with a pawn. 3...d4 kicks the knight; ...e5 then grabs space.',
    },
  },
];

export const FAMILIES: Record<OpeningId, Family[]> = { italian: [KINGS_PAWN, ...ITALIAN], 'caro-kann': [KINGS_PAWN, ...CARO_KANN] };
